// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/apigInstance:ApigInstance")]
    public partial class ApigInstance : global::Pulumi.CustomResource
    {
        /// <summary>
        /// schema: Required; The name list of availability zones for the dedicated instance.
        /// </summary>
        [Output("availabilityZones")]
        public Output<ImmutableArray<string>> AvailabilityZones { get; private set; } = null!;

        /// <summary>
        /// schema: Deprecated; The name list of availability zones for the dedicated instance.
        /// </summary>
        [Output("availableZones")]
        public Output<ImmutableArray<string>> AvailableZones { get; private set; } = null!;

        /// <summary>
        /// The egress bandwidth size of the dedicated instance.
        /// </summary>
        [Output("bandwidthSize")]
        public Output<int?> BandwidthSize { get; private set; } = null!;

        /// <summary>
        /// schema: Deprecated; Time when the dedicated instance is created.
        /// </summary>
        [Output("createTime")]
        public Output<string> CreateTime { get; private set; } = null!;

        /// <summary>
        /// Time when the dedicated instance is created, in RFC-3339 format.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Specified the list of the instance custom ingress ports.
        /// </summary>
        [Output("customIngressPorts")]
        public Output<ImmutableArray<Outputs.ApigInstanceCustomIngressPort>> CustomIngressPorts { get; private set; } = null!;

        /// <summary>
        /// The description of the dedicated instance.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The edition of the dedicated instance.
        /// </summary>
        [Output("edition")]
        public Output<string> Edition { get; private set; } = null!;

        /// <summary>
        /// The egress (NAT) public IP address.
        /// </summary>
        [Output("egressAddress")]
        public Output<string> EgressAddress { get; private set; } = null!;

        /// <summary>
        /// The EIP ID associated with the dedicated instance.
        /// </summary>
        [Output("eipId")]
        public Output<string> EipId { get; private set; } = null!;

        /// <summary>
        /// The enterprise project ID to which the dedicated instance belongs.
        /// </summary>
        [Output("enterpriseProjectId")]
        public Output<string> EnterpriseProjectId { get; private set; } = null!;

        /// <summary>
        /// The ingress EIP address.
        /// </summary>
        [Output("ingressAddress")]
        public Output<string> IngressAddress { get; private set; } = null!;

        [Output("ingressBandwidthChargingMode")]
        public Output<string?> IngressBandwidthChargingMode { get; private set; } = null!;

        [Output("ingressBandwidthSize")]
        public Output<int?> IngressBandwidthSize { get; private set; } = null!;

        /// <summary>
        /// Whether public access with an IPv6 address is supported.
        /// </summary>
        [Output("ipv6Enable")]
        public Output<bool> Ipv6Enable { get; private set; } = null!;

        /// <summary>
        /// The type of loadbalancer provider used by the instance.
        /// </summary>
        [Output("loadbalancerProvider")]
        public Output<string> LoadbalancerProvider { get; private set; } = null!;

        /// <summary>
        /// The start time of the maintenance time window.
        /// </summary>
        [Output("maintainBegin")]
        public Output<string> MaintainBegin { get; private set; } = null!;

        /// <summary>
        /// End time of the maintenance time window, 4-hour difference between the start time and end time.
        /// </summary>
        [Output("maintainEnd")]
        public Output<string> MaintainEnd { get; private set; } = null!;

        /// <summary>
        /// The name of the dedicated instance.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The region in which to create the dedicated instance resource.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// The ID of the security group to which the dedicated instance belongs to.
        /// </summary>
        [Output("securityGroupId")]
        public Output<string> SecurityGroupId { get; private set; } = null!;

        /// <summary>
        /// Status of the dedicated instance.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// The ID of the VPC subnet used to create the dedicated instance.
        /// </summary>
        [Output("subnetId")]
        public Output<string> SubnetId { get; private set; } = null!;

        /// <summary>
        /// The supported features of the dedicated instance.
        /// </summary>
        [Output("supportedFeatures")]
        public Output<ImmutableArray<string>> SupportedFeatures { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        /// <summary>
        /// The ID of the VPC used to create the dedicated instance.
        /// </summary>
        [Output("vpcId")]
        public Output<string> VpcId { get; private set; } = null!;

        /// <summary>
        /// The ingress private IP address of the VPC.
        /// </summary>
        [Output("vpcIngressAddress")]
        public Output<string> VpcIngressAddress { get; private set; } = null!;

        /// <summary>
        /// The address (full name) of the VPC endpoint service.
        /// </summary>
        [Output("vpcepServiceAddress")]
        public Output<string> VpcepServiceAddress { get; private set; } = null!;

        /// <summary>
        /// Name of the VPC endpoint service.
        /// </summary>
        [Output("vpcepServiceName")]
        public Output<string> VpcepServiceName { get; private set; } = null!;


        /// <summary>
        /// Create a ApigInstance resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApigInstance(string name, ApigInstanceArgs args, CustomResourceOptions? options = null)
            : base("sbercloud:index/apigInstance:ApigInstance", name, args ?? new ApigInstanceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApigInstance(string name, Input<string> id, ApigInstanceState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/apigInstance:ApigInstance", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApigInstance resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApigInstance Get(string name, Input<string> id, ApigInstanceState? state = null, CustomResourceOptions? options = null)
        {
            return new ApigInstance(name, id, state, options);
        }
    }

    public sealed class ApigInstanceArgs : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZones")]
        private InputList<string>? _availabilityZones;

        /// <summary>
        /// schema: Required; The name list of availability zones for the dedicated instance.
        /// </summary>
        public InputList<string> AvailabilityZones
        {
            get => _availabilityZones ?? (_availabilityZones = new InputList<string>());
            set => _availabilityZones = value;
        }

        [Input("availableZones")]
        private InputList<string>? _availableZones;

        /// <summary>
        /// schema: Deprecated; The name list of availability zones for the dedicated instance.
        /// </summary>
        public InputList<string> AvailableZones
        {
            get => _availableZones ?? (_availableZones = new InputList<string>());
            set => _availableZones = value;
        }

        /// <summary>
        /// The egress bandwidth size of the dedicated instance.
        /// </summary>
        [Input("bandwidthSize")]
        public Input<int>? BandwidthSize { get; set; }

        [Input("customIngressPorts")]
        private InputList<Inputs.ApigInstanceCustomIngressPortArgs>? _customIngressPorts;

        /// <summary>
        /// Specified the list of the instance custom ingress ports.
        /// </summary>
        public InputList<Inputs.ApigInstanceCustomIngressPortArgs> CustomIngressPorts
        {
            get => _customIngressPorts ?? (_customIngressPorts = new InputList<Inputs.ApigInstanceCustomIngressPortArgs>());
            set => _customIngressPorts = value;
        }

        /// <summary>
        /// The description of the dedicated instance.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The edition of the dedicated instance.
        /// </summary>
        [Input("edition", required: true)]
        public Input<string> Edition { get; set; } = null!;

        /// <summary>
        /// The EIP ID associated with the dedicated instance.
        /// </summary>
        [Input("eipId")]
        public Input<string>? EipId { get; set; }

        /// <summary>
        /// The enterprise project ID to which the dedicated instance belongs.
        /// </summary>
        [Input("enterpriseProjectId")]
        public Input<string>? EnterpriseProjectId { get; set; }

        [Input("ingressBandwidthChargingMode")]
        public Input<string>? IngressBandwidthChargingMode { get; set; }

        [Input("ingressBandwidthSize")]
        public Input<int>? IngressBandwidthSize { get; set; }

        /// <summary>
        /// Whether public access with an IPv6 address is supported.
        /// </summary>
        [Input("ipv6Enable")]
        public Input<bool>? Ipv6Enable { get; set; }

        /// <summary>
        /// The type of loadbalancer provider used by the instance.
        /// </summary>
        [Input("loadbalancerProvider")]
        public Input<string>? LoadbalancerProvider { get; set; }

        /// <summary>
        /// The start time of the maintenance time window.
        /// </summary>
        [Input("maintainBegin")]
        public Input<string>? MaintainBegin { get; set; }

        /// <summary>
        /// The name of the dedicated instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The region in which to create the dedicated instance resource.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The ID of the security group to which the dedicated instance belongs to.
        /// </summary>
        [Input("securityGroupId", required: true)]
        public Input<string> SecurityGroupId { get; set; } = null!;

        /// <summary>
        /// The ID of the VPC subnet used to create the dedicated instance.
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The ID of the VPC used to create the dedicated instance.
        /// </summary>
        [Input("vpcId", required: true)]
        public Input<string> VpcId { get; set; } = null!;

        /// <summary>
        /// Name of the VPC endpoint service.
        /// </summary>
        [Input("vpcepServiceName")]
        public Input<string>? VpcepServiceName { get; set; }

        public ApigInstanceArgs()
        {
        }
        public static new ApigInstanceArgs Empty => new ApigInstanceArgs();
    }

    public sealed class ApigInstanceState : global::Pulumi.ResourceArgs
    {
        [Input("availabilityZones")]
        private InputList<string>? _availabilityZones;

        /// <summary>
        /// schema: Required; The name list of availability zones for the dedicated instance.
        /// </summary>
        public InputList<string> AvailabilityZones
        {
            get => _availabilityZones ?? (_availabilityZones = new InputList<string>());
            set => _availabilityZones = value;
        }

        [Input("availableZones")]
        private InputList<string>? _availableZones;

        /// <summary>
        /// schema: Deprecated; The name list of availability zones for the dedicated instance.
        /// </summary>
        public InputList<string> AvailableZones
        {
            get => _availableZones ?? (_availableZones = new InputList<string>());
            set => _availableZones = value;
        }

        /// <summary>
        /// The egress bandwidth size of the dedicated instance.
        /// </summary>
        [Input("bandwidthSize")]
        public Input<int>? BandwidthSize { get; set; }

        /// <summary>
        /// schema: Deprecated; Time when the dedicated instance is created.
        /// </summary>
        [Input("createTime")]
        public Input<string>? CreateTime { get; set; }

        /// <summary>
        /// Time when the dedicated instance is created, in RFC-3339 format.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("customIngressPorts")]
        private InputList<Inputs.ApigInstanceCustomIngressPortGetArgs>? _customIngressPorts;

        /// <summary>
        /// Specified the list of the instance custom ingress ports.
        /// </summary>
        public InputList<Inputs.ApigInstanceCustomIngressPortGetArgs> CustomIngressPorts
        {
            get => _customIngressPorts ?? (_customIngressPorts = new InputList<Inputs.ApigInstanceCustomIngressPortGetArgs>());
            set => _customIngressPorts = value;
        }

        /// <summary>
        /// The description of the dedicated instance.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The edition of the dedicated instance.
        /// </summary>
        [Input("edition")]
        public Input<string>? Edition { get; set; }

        /// <summary>
        /// The egress (NAT) public IP address.
        /// </summary>
        [Input("egressAddress")]
        public Input<string>? EgressAddress { get; set; }

        /// <summary>
        /// The EIP ID associated with the dedicated instance.
        /// </summary>
        [Input("eipId")]
        public Input<string>? EipId { get; set; }

        /// <summary>
        /// The enterprise project ID to which the dedicated instance belongs.
        /// </summary>
        [Input("enterpriseProjectId")]
        public Input<string>? EnterpriseProjectId { get; set; }

        /// <summary>
        /// The ingress EIP address.
        /// </summary>
        [Input("ingressAddress")]
        public Input<string>? IngressAddress { get; set; }

        [Input("ingressBandwidthChargingMode")]
        public Input<string>? IngressBandwidthChargingMode { get; set; }

        [Input("ingressBandwidthSize")]
        public Input<int>? IngressBandwidthSize { get; set; }

        /// <summary>
        /// Whether public access with an IPv6 address is supported.
        /// </summary>
        [Input("ipv6Enable")]
        public Input<bool>? Ipv6Enable { get; set; }

        /// <summary>
        /// The type of loadbalancer provider used by the instance.
        /// </summary>
        [Input("loadbalancerProvider")]
        public Input<string>? LoadbalancerProvider { get; set; }

        /// <summary>
        /// The start time of the maintenance time window.
        /// </summary>
        [Input("maintainBegin")]
        public Input<string>? MaintainBegin { get; set; }

        /// <summary>
        /// End time of the maintenance time window, 4-hour difference between the start time and end time.
        /// </summary>
        [Input("maintainEnd")]
        public Input<string>? MaintainEnd { get; set; }

        /// <summary>
        /// The name of the dedicated instance.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The region in which to create the dedicated instance resource.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The ID of the security group to which the dedicated instance belongs to.
        /// </summary>
        [Input("securityGroupId")]
        public Input<string>? SecurityGroupId { get; set; }

        /// <summary>
        /// Status of the dedicated instance.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// The ID of the VPC subnet used to create the dedicated instance.
        /// </summary>
        [Input("subnetId")]
        public Input<string>? SubnetId { get; set; }

        [Input("supportedFeatures")]
        private InputList<string>? _supportedFeatures;

        /// <summary>
        /// The supported features of the dedicated instance.
        /// </summary>
        public InputList<string> SupportedFeatures
        {
            get => _supportedFeatures ?? (_supportedFeatures = new InputList<string>());
            set => _supportedFeatures = value;
        }

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The ID of the VPC used to create the dedicated instance.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        /// <summary>
        /// The ingress private IP address of the VPC.
        /// </summary>
        [Input("vpcIngressAddress")]
        public Input<string>? VpcIngressAddress { get; set; }

        /// <summary>
        /// The address (full name) of the VPC endpoint service.
        /// </summary>
        [Input("vpcepServiceAddress")]
        public Input<string>? VpcepServiceAddress { get; set; }

        /// <summary>
        /// Name of the VPC endpoint service.
        /// </summary>
        [Input("vpcepServiceName")]
        public Input<string>? VpcepServiceName { get; set; }

        public ApigInstanceState()
        {
        }
        public static new ApigInstanceState Empty => new ApigInstanceState();
    }
}
