// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/cfwAddressGroupMember:CfwAddressGroupMember")]
    public partial class CfwAddressGroupMember : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Specifies the IP address.
        /// </summary>
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        /// <summary>
        /// Specifies the address type.
        /// </summary>
        [Output("addressType")]
        public Output<int> AddressType { get; private set; } = null!;

        /// <summary>
        /// Specifies address description.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Specifies the ID of the IP address group.
        /// </summary>
        [Output("groupId")]
        public Output<string> GroupId { get; private set; } = null!;

        /// <summary>
        /// schema: Deprecated; Specifies the address name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a CfwAddressGroupMember resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CfwAddressGroupMember(string name, CfwAddressGroupMemberArgs args, CustomResourceOptions? options = null)
            : base("sbercloud:index/cfwAddressGroupMember:CfwAddressGroupMember", name, args ?? new CfwAddressGroupMemberArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CfwAddressGroupMember(string name, Input<string> id, CfwAddressGroupMemberState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/cfwAddressGroupMember:CfwAddressGroupMember", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CfwAddressGroupMember resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CfwAddressGroupMember Get(string name, Input<string> id, CfwAddressGroupMemberState? state = null, CustomResourceOptions? options = null)
        {
            return new CfwAddressGroupMember(name, id, state, options);
        }
    }

    public sealed class CfwAddressGroupMemberArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the IP address.
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        /// <summary>
        /// Specifies the address type.
        /// </summary>
        [Input("addressType")]
        public Input<int>? AddressType { get; set; }

        /// <summary>
        /// Specifies address description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Specifies the ID of the IP address group.
        /// </summary>
        [Input("groupId", required: true)]
        public Input<string> GroupId { get; set; } = null!;

        /// <summary>
        /// schema: Deprecated; Specifies the address name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public CfwAddressGroupMemberArgs()
        {
        }
        public static new CfwAddressGroupMemberArgs Empty => new CfwAddressGroupMemberArgs();
    }

    public sealed class CfwAddressGroupMemberState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the IP address.
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// Specifies the address type.
        /// </summary>
        [Input("addressType")]
        public Input<int>? AddressType { get; set; }

        /// <summary>
        /// Specifies address description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Specifies the ID of the IP address group.
        /// </summary>
        [Input("groupId")]
        public Input<string>? GroupId { get; set; }

        /// <summary>
        /// schema: Deprecated; Specifies the address name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public CfwAddressGroupMemberState()
        {
        }
        public static new CfwAddressGroupMemberState Empty => new CfwAddressGroupMemberState();
    }
}
