// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/ddsParameterTemplateCompare:DdsParameterTemplateCompare")]
    public partial class DdsParameterTemplateCompare : global::Pulumi.CustomResource
    {
        [Output("differences")]
        public Output<ImmutableArray<Outputs.DdsParameterTemplateCompareDifference>> Differences { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        [Output("sourceConfigurationId")]
        public Output<string> SourceConfigurationId { get; private set; } = null!;

        [Output("targetConfigurationId")]
        public Output<string> TargetConfigurationId { get; private set; } = null!;


        /// <summary>
        /// Create a DdsParameterTemplateCompare resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DdsParameterTemplateCompare(string name, DdsParameterTemplateCompareArgs args, CustomResourceOptions? options = null)
            : base("sbercloud:index/ddsParameterTemplateCompare:DdsParameterTemplateCompare", name, args ?? new DdsParameterTemplateCompareArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DdsParameterTemplateCompare(string name, Input<string> id, DdsParameterTemplateCompareState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/ddsParameterTemplateCompare:DdsParameterTemplateCompare", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DdsParameterTemplateCompare resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DdsParameterTemplateCompare Get(string name, Input<string> id, DdsParameterTemplateCompareState? state = null, CustomResourceOptions? options = null)
        {
            return new DdsParameterTemplateCompare(name, id, state, options);
        }
    }

    public sealed class DdsParameterTemplateCompareArgs : global::Pulumi.ResourceArgs
    {
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("sourceConfigurationId", required: true)]
        public Input<string> SourceConfigurationId { get; set; } = null!;

        [Input("targetConfigurationId", required: true)]
        public Input<string> TargetConfigurationId { get; set; } = null!;

        public DdsParameterTemplateCompareArgs()
        {
        }
        public static new DdsParameterTemplateCompareArgs Empty => new DdsParameterTemplateCompareArgs();
    }

    public sealed class DdsParameterTemplateCompareState : global::Pulumi.ResourceArgs
    {
        [Input("differences")]
        private InputList<Inputs.DdsParameterTemplateCompareDifferenceGetArgs>? _differences;
        public InputList<Inputs.DdsParameterTemplateCompareDifferenceGetArgs> Differences
        {
            get => _differences ?? (_differences = new InputList<Inputs.DdsParameterTemplateCompareDifferenceGetArgs>());
            set => _differences = value;
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("sourceConfigurationId")]
        public Input<string>? SourceConfigurationId { get; set; }

        [Input("targetConfigurationId")]
        public Input<string>? TargetConfigurationId { get; set; }

        public DdsParameterTemplateCompareState()
        {
        }
        public static new DdsParameterTemplateCompareState Empty => new DdsParameterTemplateCompareState();
    }
}
