// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/ddsParameterTemplateApply:DdsParameterTemplateApply")]
    public partial class DdsParameterTemplateApply : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Specifies the parameter template ID.
        /// </summary>
        [Output("configurationId")]
        public Output<string> ConfigurationId { get; private set; } = null!;

        /// <summary>
        /// Specifies the entity IDs.
        /// </summary>
        [Output("entityIds")]
        public Output<ImmutableArray<string>> EntityIds { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a DdsParameterTemplateApply resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DdsParameterTemplateApply(string name, DdsParameterTemplateApplyArgs args, CustomResourceOptions? options = null)
            : base("sbercloud:index/ddsParameterTemplateApply:DdsParameterTemplateApply", name, args ?? new DdsParameterTemplateApplyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DdsParameterTemplateApply(string name, Input<string> id, DdsParameterTemplateApplyState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/ddsParameterTemplateApply:DdsParameterTemplateApply", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DdsParameterTemplateApply resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DdsParameterTemplateApply Get(string name, Input<string> id, DdsParameterTemplateApplyState? state = null, CustomResourceOptions? options = null)
        {
            return new DdsParameterTemplateApply(name, id, state, options);
        }
    }

    public sealed class DdsParameterTemplateApplyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the parameter template ID.
        /// </summary>
        [Input("configurationId", required: true)]
        public Input<string> ConfigurationId { get; set; } = null!;

        [Input("entityIds", required: true)]
        private InputList<string>? _entityIds;

        /// <summary>
        /// Specifies the entity IDs.
        /// </summary>
        public InputList<string> EntityIds
        {
            get => _entityIds ?? (_entityIds = new InputList<string>());
            set => _entityIds = value;
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public DdsParameterTemplateApplyArgs()
        {
        }
        public static new DdsParameterTemplateApplyArgs Empty => new DdsParameterTemplateApplyArgs();
    }

    public sealed class DdsParameterTemplateApplyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the parameter template ID.
        /// </summary>
        [Input("configurationId")]
        public Input<string>? ConfigurationId { get; set; }

        [Input("entityIds")]
        private InputList<string>? _entityIds;

        /// <summary>
        /// Specifies the entity IDs.
        /// </summary>
        public InputList<string> EntityIds
        {
            get => _entityIds ?? (_entityIds = new InputList<string>());
            set => _entityIds = value;
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public DdsParameterTemplateApplyState()
        {
        }
        public static new DdsParameterTemplateApplyState Empty => new DdsParameterTemplateApplyState();
    }
}
