// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/fgsDependency:FgsDependency")]
    public partial class FgsDependency : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The description of the dependency package.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The etag of the dependency package.
        /// </summary>
        [Output("etag")]
        public Output<string> Etag { get; private set; } = null!;

        /// <summary>
        /// The OBS storage URL of the dependency package.
        /// </summary>
        [Output("link")]
        public Output<string> Link { get; private set; } = null!;

        /// <summary>
        /// The name of the dependency package.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The owner name of the dependency package.
        /// </summary>
        [Output("owner")]
        public Output<string> Owner { get; private set; } = null!;

        /// <summary>
        /// The region where the dependency package is located.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// The runtime of the dependency package.
        /// </summary>
        [Output("runtime")]
        public Output<string> Runtime { get; private set; } = null!;

        /// <summary>
        /// The capacity of the dependency package.
        /// </summary>
        [Output("size")]
        public Output<int> Size { get; private set; } = null!;

        /// <summary>
        /// The version of the dependency package.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a FgsDependency resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FgsDependency(string name, FgsDependencyArgs args, CustomResourceOptions? options = null)
            : base("sbercloud:index/fgsDependency:FgsDependency", name, args ?? new FgsDependencyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FgsDependency(string name, Input<string> id, FgsDependencyState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/fgsDependency:FgsDependency", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FgsDependency resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FgsDependency Get(string name, Input<string> id, FgsDependencyState? state = null, CustomResourceOptions? options = null)
        {
            return new FgsDependency(name, id, state, options);
        }
    }

    public sealed class FgsDependencyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the dependency package.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The OBS storage URL of the dependency package.
        /// </summary>
        [Input("link", required: true)]
        public Input<string> Link { get; set; } = null!;

        /// <summary>
        /// The name of the dependency package.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The region where the dependency package is located.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The runtime of the dependency package.
        /// </summary>
        [Input("runtime", required: true)]
        public Input<string> Runtime { get; set; } = null!;

        public FgsDependencyArgs()
        {
        }
        public static new FgsDependencyArgs Empty => new FgsDependencyArgs();
    }

    public sealed class FgsDependencyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of the dependency package.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The etag of the dependency package.
        /// </summary>
        [Input("etag")]
        public Input<string>? Etag { get; set; }

        /// <summary>
        /// The OBS storage URL of the dependency package.
        /// </summary>
        [Input("link")]
        public Input<string>? Link { get; set; }

        /// <summary>
        /// The name of the dependency package.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The owner name of the dependency package.
        /// </summary>
        [Input("owner")]
        public Input<string>? Owner { get; set; }

        /// <summary>
        /// The region where the dependency package is located.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The runtime of the dependency package.
        /// </summary>
        [Input("runtime")]
        public Input<string>? Runtime { get; set; }

        /// <summary>
        /// The capacity of the dependency package.
        /// </summary>
        [Input("size")]
        public Input<int>? Size { get; set; }

        /// <summary>
        /// The version of the dependency package.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public FgsDependencyState()
        {
        }
        public static new FgsDependencyState Empty => new FgsDependencyState();
    }
}
