// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetApigApiAssociatedApplications
    {
        public static Task<GetApigApiAssociatedApplicationsResult> InvokeAsync(GetApigApiAssociatedApplicationsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetApigApiAssociatedApplicationsResult>("sbercloud:index/getApigApiAssociatedApplications:getApigApiAssociatedApplications", args ?? new GetApigApiAssociatedApplicationsArgs(), options.WithDefaults());

        public static Output<GetApigApiAssociatedApplicationsResult> Invoke(GetApigApiAssociatedApplicationsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetApigApiAssociatedApplicationsResult>("sbercloud:index/getApigApiAssociatedApplications:getApigApiAssociatedApplications", args ?? new GetApigApiAssociatedApplicationsInvokeArgs(), options.WithDefaults());

        public static Output<GetApigApiAssociatedApplicationsResult> Invoke(GetApigApiAssociatedApplicationsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetApigApiAssociatedApplicationsResult>("sbercloud:index/getApigApiAssociatedApplications:getApigApiAssociatedApplications", args ?? new GetApigApiAssociatedApplicationsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetApigApiAssociatedApplicationsArgs : global::Pulumi.InvokeArgs
    {
        [Input("apiId", required: true)]
        public string ApiId { get; set; } = null!;

        [Input("applicationId")]
        public string? ApplicationId { get; set; }

        [Input("envId")]
        public string? EnvId { get; set; }

        [Input("envName")]
        public string? EnvName { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("name")]
        public string? Name { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        public GetApigApiAssociatedApplicationsArgs()
        {
        }
        public static new GetApigApiAssociatedApplicationsArgs Empty => new GetApigApiAssociatedApplicationsArgs();
    }

    public sealed class GetApigApiAssociatedApplicationsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("apiId", required: true)]
        public Input<string> ApiId { get; set; } = null!;

        [Input("applicationId")]
        public Input<string>? ApplicationId { get; set; }

        [Input("envId")]
        public Input<string>? EnvId { get; set; }

        [Input("envName")]
        public Input<string>? EnvName { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetApigApiAssociatedApplicationsInvokeArgs()
        {
        }
        public static new GetApigApiAssociatedApplicationsInvokeArgs Empty => new GetApigApiAssociatedApplicationsInvokeArgs();
    }


    [OutputType]
    public sealed class GetApigApiAssociatedApplicationsResult
    {
        public readonly string ApiId;
        public readonly string? ApplicationId;
        public readonly ImmutableArray<Outputs.GetApigApiAssociatedApplicationsApplicationResult> Applications;
        public readonly string? EnvId;
        public readonly string? EnvName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string? Name;
        public readonly string Region;

        [OutputConstructor]
        private GetApigApiAssociatedApplicationsResult(
            string apiId,

            string? applicationId,

            ImmutableArray<Outputs.GetApigApiAssociatedApplicationsApplicationResult> applications,

            string? envId,

            string? envName,

            string id,

            string instanceId,

            string? name,

            string region)
        {
            ApiId = apiId;
            ApplicationId = applicationId;
            Applications = applications;
            EnvId = envId;
            EnvName = envName;
            Id = id;
            InstanceId = instanceId;
            Name = name;
            Region = region;
        }
    }
}
