// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetApigChannels
    {
        public static Task<GetApigChannelsResult> InvokeAsync(GetApigChannelsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetApigChannelsResult>("sbercloud:index/getApigChannels:getApigChannels", args ?? new GetApigChannelsArgs(), options.WithDefaults());

        public static Output<GetApigChannelsResult> Invoke(GetApigChannelsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetApigChannelsResult>("sbercloud:index/getApigChannels:getApigChannels", args ?? new GetApigChannelsInvokeArgs(), options.WithDefaults());

        public static Output<GetApigChannelsResult> Invoke(GetApigChannelsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetApigChannelsResult>("sbercloud:index/getApigChannels:getApigChannels", args ?? new GetApigChannelsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetApigChannelsArgs : global::Pulumi.InvokeArgs
    {
        [Input("channelId")]
        public string? ChannelId { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("memberGroupId")]
        public string? MemberGroupId { get; set; }

        [Input("memberGroupName")]
        public string? MemberGroupName { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("preciseSearch")]
        public string? PreciseSearch { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        public GetApigChannelsArgs()
        {
        }
        public static new GetApigChannelsArgs Empty => new GetApigChannelsArgs();
    }

    public sealed class GetApigChannelsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("channelId")]
        public Input<string>? ChannelId { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("memberGroupId")]
        public Input<string>? MemberGroupId { get; set; }

        [Input("memberGroupName")]
        public Input<string>? MemberGroupName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("preciseSearch")]
        public Input<string>? PreciseSearch { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetApigChannelsInvokeArgs()
        {
        }
        public static new GetApigChannelsInvokeArgs Empty => new GetApigChannelsInvokeArgs();
    }


    [OutputType]
    public sealed class GetApigChannelsResult
    {
        public readonly string? ChannelId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string? MemberGroupId;
        public readonly string? MemberGroupName;
        public readonly string? Name;
        public readonly string? PreciseSearch;
        public readonly string Region;
        public readonly ImmutableArray<Outputs.GetApigChannelsVpcChannelResult> VpcChannels;

        [OutputConstructor]
        private GetApigChannelsResult(
            string? channelId,

            string id,

            string instanceId,

            string? memberGroupId,

            string? memberGroupName,

            string? name,

            string? preciseSearch,

            string region,

            ImmutableArray<Outputs.GetApigChannelsVpcChannelResult> vpcChannels)
        {
            ChannelId = channelId;
            Id = id;
            InstanceId = instanceId;
            MemberGroupId = memberGroupId;
            MemberGroupName = memberGroupName;
            Name = name;
            PreciseSearch = preciseSearch;
            Region = region;
            VpcChannels = vpcChannels;
        }
    }
}
