// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetCfwCaptureTaskResults
    {
        public static Task<GetCfwCaptureTaskResultsResult> InvokeAsync(GetCfwCaptureTaskResultsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCfwCaptureTaskResultsResult>("sbercloud:index/getCfwCaptureTaskResults:getCfwCaptureTaskResults", args ?? new GetCfwCaptureTaskResultsArgs(), options.WithDefaults());

        public static Output<GetCfwCaptureTaskResultsResult> Invoke(GetCfwCaptureTaskResultsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCfwCaptureTaskResultsResult>("sbercloud:index/getCfwCaptureTaskResults:getCfwCaptureTaskResults", args ?? new GetCfwCaptureTaskResultsInvokeArgs(), options.WithDefaults());

        public static Output<GetCfwCaptureTaskResultsResult> Invoke(GetCfwCaptureTaskResultsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetCfwCaptureTaskResultsResult>("sbercloud:index/getCfwCaptureTaskResults:getCfwCaptureTaskResults", args ?? new GetCfwCaptureTaskResultsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCfwCaptureTaskResultsArgs : global::Pulumi.InvokeArgs
    {
        [Input("fwInstanceId", required: true)]
        public string FwInstanceId { get; set; } = null!;

        [Input("ips")]
        private List<string>? _ips;
        public List<string> Ips
        {
            get => _ips ?? (_ips = new List<string>());
            set => _ips = value;
        }

        [Input("region")]
        public string? Region { get; set; }

        [Input("taskId", required: true)]
        public string TaskId { get; set; } = null!;

        [Input("type")]
        public int? Type { get; set; }

        public GetCfwCaptureTaskResultsArgs()
        {
        }
        public static new GetCfwCaptureTaskResultsArgs Empty => new GetCfwCaptureTaskResultsArgs();
    }

    public sealed class GetCfwCaptureTaskResultsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("fwInstanceId", required: true)]
        public Input<string> FwInstanceId { get; set; } = null!;

        [Input("ips")]
        private InputList<string>? _ips;
        public InputList<string> Ips
        {
            get => _ips ?? (_ips = new InputList<string>());
            set => _ips = value;
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("taskId", required: true)]
        public Input<string> TaskId { get; set; } = null!;

        [Input("type")]
        public Input<int>? Type { get; set; }

        public GetCfwCaptureTaskResultsInvokeArgs()
        {
        }
        public static new GetCfwCaptureTaskResultsInvokeArgs Empty => new GetCfwCaptureTaskResultsInvokeArgs();
    }


    [OutputType]
    public sealed class GetCfwCaptureTaskResultsResult
    {
        public readonly string Captcha;
        public readonly int Expires;
        public readonly ImmutableArray<Outputs.GetCfwCaptureTaskResultsFileListResult> FileLists;
        public readonly string FwInstanceId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ips;
        public readonly string Region;
        public readonly ImmutableArray<Outputs.GetCfwCaptureTaskResultsRequestHeaderResult> RequestHeaders;
        public readonly string TaskId;
        public readonly int? Type;
        public readonly string Url;

        [OutputConstructor]
        private GetCfwCaptureTaskResultsResult(
            string captcha,

            int expires,

            ImmutableArray<Outputs.GetCfwCaptureTaskResultsFileListResult> fileLists,

            string fwInstanceId,

            string id,

            ImmutableArray<string> ips,

            string region,

            ImmutableArray<Outputs.GetCfwCaptureTaskResultsRequestHeaderResult> requestHeaders,

            string taskId,

            int? type,

            string url)
        {
            Captcha = captcha;
            Expires = expires;
            FileLists = fileLists;
            FwInstanceId = fwInstanceId;
            Id = id;
            Ips = ips;
            Region = region;
            RequestHeaders = requestHeaders;
            TaskId = taskId;
            Type = type;
            Url = url;
        }
    }
}
