// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetDmsKafkaUsers
    {
        public static Task<GetDmsKafkaUsersResult> InvokeAsync(GetDmsKafkaUsersArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDmsKafkaUsersResult>("sbercloud:index/getDmsKafkaUsers:getDmsKafkaUsers", args ?? new GetDmsKafkaUsersArgs(), options.WithDefaults());

        public static Output<GetDmsKafkaUsersResult> Invoke(GetDmsKafkaUsersInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDmsKafkaUsersResult>("sbercloud:index/getDmsKafkaUsers:getDmsKafkaUsers", args ?? new GetDmsKafkaUsersInvokeArgs(), options.WithDefaults());

        public static Output<GetDmsKafkaUsersResult> Invoke(GetDmsKafkaUsersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDmsKafkaUsersResult>("sbercloud:index/getDmsKafkaUsers:getDmsKafkaUsers", args ?? new GetDmsKafkaUsersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDmsKafkaUsersArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public string? Description { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("name")]
        public string? Name { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        public GetDmsKafkaUsersArgs()
        {
        }
        public static new GetDmsKafkaUsersArgs Empty => new GetDmsKafkaUsersArgs();
    }

    public sealed class GetDmsKafkaUsersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetDmsKafkaUsersInvokeArgs()
        {
        }
        public static new GetDmsKafkaUsersInvokeArgs Empty => new GetDmsKafkaUsersInvokeArgs();
    }


    [OutputType]
    public sealed class GetDmsKafkaUsersResult
    {
        public readonly string? Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string? Name;
        public readonly string Region;
        public readonly ImmutableArray<Outputs.GetDmsKafkaUsersUserResult> Users;

        [OutputConstructor]
        private GetDmsKafkaUsersResult(
            string? description,

            string id,

            string instanceId,

            string? name,

            string region,

            ImmutableArray<Outputs.GetDmsKafkaUsersUserResult> users)
        {
            Description = description;
            Id = id;
            InstanceId = instanceId;
            Name = name;
            Region = region;
            Users = users;
        }
    }
}
