// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetErAttachments
    {
        public static Task<GetErAttachmentsResult> InvokeAsync(GetErAttachmentsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetErAttachmentsResult>("sbercloud:index/getErAttachments:getErAttachments", args ?? new GetErAttachmentsArgs(), options.WithDefaults());

        public static Output<GetErAttachmentsResult> Invoke(GetErAttachmentsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetErAttachmentsResult>("sbercloud:index/getErAttachments:getErAttachments", args ?? new GetErAttachmentsInvokeArgs(), options.WithDefaults());

        public static Output<GetErAttachmentsResult> Invoke(GetErAttachmentsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetErAttachmentsResult>("sbercloud:index/getErAttachments:getErAttachments", args ?? new GetErAttachmentsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetErAttachmentsArgs : global::Pulumi.InvokeArgs
    {
        [Input("attachmentId")]
        public string? AttachmentId { get; set; }

        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        [Input("name")]
        public string? Name { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        [Input("resourceId")]
        public string? ResourceId { get; set; }

        [Input("status")]
        public string? Status { get; set; }

        [Input("tags")]
        private Dictionary<string, string>? _tags;
        public Dictionary<string, string> Tags
        {
            get => _tags ?? (_tags = new Dictionary<string, string>());
            set => _tags = value;
        }

        [Input("type")]
        public string? Type { get; set; }

        public GetErAttachmentsArgs()
        {
        }
        public static new GetErAttachmentsArgs Empty => new GetErAttachmentsArgs();
    }

    public sealed class GetErAttachmentsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("attachmentId")]
        public Input<string>? AttachmentId { get; set; }

        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("resourceId")]
        public Input<string>? ResourceId { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public GetErAttachmentsInvokeArgs()
        {
        }
        public static new GetErAttachmentsInvokeArgs Empty => new GetErAttachmentsInvokeArgs();
    }


    [OutputType]
    public sealed class GetErAttachmentsResult
    {
        public readonly string? AttachmentId;
        public readonly ImmutableArray<Outputs.GetErAttachmentsAttachmentResult> Attachments;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string? Name;
        public readonly string? Region;
        public readonly string? ResourceId;
        public readonly string? Status;
        public readonly ImmutableDictionary<string, string>? Tags;
        public readonly string? Type;

        [OutputConstructor]
        private GetErAttachmentsResult(
            string? attachmentId,

            ImmutableArray<Outputs.GetErAttachmentsAttachmentResult> attachments,

            string id,

            string instanceId,

            string? name,

            string? region,

            string? resourceId,

            string? status,

            ImmutableDictionary<string, string>? tags,

            string? type)
        {
            AttachmentId = attachmentId;
            Attachments = attachments;
            Id = id;
            InstanceId = instanceId;
            Name = name;
            Region = region;
            ResourceId = resourceId;
            Status = status;
            Tags = tags;
            Type = type;
        }
    }
}
