// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetIdentityUsers
    {
        public static Task<GetIdentityUsersResult> InvokeAsync(GetIdentityUsersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIdentityUsersResult>("sbercloud:index/getIdentityUsers:getIdentityUsers", args ?? new GetIdentityUsersArgs(), options.WithDefaults());

        public static Output<GetIdentityUsersResult> Invoke(GetIdentityUsersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIdentityUsersResult>("sbercloud:index/getIdentityUsers:getIdentityUsers", args ?? new GetIdentityUsersInvokeArgs(), options.WithDefaults());

        public static Output<GetIdentityUsersResult> Invoke(GetIdentityUsersInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIdentityUsersResult>("sbercloud:index/getIdentityUsers:getIdentityUsers", args ?? new GetIdentityUsersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIdentityUsersArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled")]
        public bool? Enabled { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        public GetIdentityUsersArgs()
        {
        }
        public static new GetIdentityUsersArgs Empty => new GetIdentityUsersArgs();
    }

    public sealed class GetIdentityUsersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetIdentityUsersInvokeArgs()
        {
        }
        public static new GetIdentityUsersInvokeArgs Empty => new GetIdentityUsersInvokeArgs();
    }


    [OutputType]
    public sealed class GetIdentityUsersResult
    {
        public readonly bool? Enabled;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.GetIdentityUsersUserResult> Users;

        [OutputConstructor]
        private GetIdentityUsersResult(
            bool? enabled,

            string id,

            string? name,

            ImmutableArray<Outputs.GetIdentityUsersUserResult> users)
        {
            Enabled = enabled;
            Id = id;
            Name = name;
            Users = users;
        }
    }
}
