// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetObsBuckets
    {
        public static Task<GetObsBucketsResult> InvokeAsync(GetObsBucketsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetObsBucketsResult>("sbercloud:index/getObsBuckets:getObsBuckets", args ?? new GetObsBucketsArgs(), options.WithDefaults());

        public static Output<GetObsBucketsResult> Invoke(GetObsBucketsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetObsBucketsResult>("sbercloud:index/getObsBuckets:getObsBuckets", args ?? new GetObsBucketsInvokeArgs(), options.WithDefaults());

        public static Output<GetObsBucketsResult> Invoke(GetObsBucketsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetObsBucketsResult>("sbercloud:index/getObsBuckets:getObsBuckets", args ?? new GetObsBucketsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetObsBucketsArgs : global::Pulumi.InvokeArgs
    {
        [Input("bucket")]
        public string? Bucket { get; set; }

        [Input("enterpriseProjectId")]
        public string? EnterpriseProjectId { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        public GetObsBucketsArgs()
        {
        }
        public static new GetObsBucketsArgs Empty => new GetObsBucketsArgs();
    }

    public sealed class GetObsBucketsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        [Input("enterpriseProjectId")]
        public Input<string>? EnterpriseProjectId { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetObsBucketsInvokeArgs()
        {
        }
        public static new GetObsBucketsInvokeArgs Empty => new GetObsBucketsInvokeArgs();
    }


    [OutputType]
    public sealed class GetObsBucketsResult
    {
        public readonly string? Bucket;
        public readonly ImmutableArray<Outputs.GetObsBucketsBucketResult> Buckets;
        public readonly string? EnterpriseProjectId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Region;

        [OutputConstructor]
        private GetObsBucketsResult(
            string? bucket,

            ImmutableArray<Outputs.GetObsBucketsBucketResult> buckets,

            string? enterpriseProjectId,

            string id,

            string? region)
        {
            Bucket = bucket;
            Buckets = buckets;
            EnterpriseProjectId = enterpriseProjectId;
            Id = id;
            Region = region;
        }
    }
}
