// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    public static class GetVpcPeeringConnection
    {
        public static Task<GetVpcPeeringConnectionResult> InvokeAsync(GetVpcPeeringConnectionArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpcPeeringConnectionResult>("sbercloud:index/getVpcPeeringConnection:getVpcPeeringConnection", args ?? new GetVpcPeeringConnectionArgs(), options.WithDefaults());

        public static Output<GetVpcPeeringConnectionResult> Invoke(GetVpcPeeringConnectionInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcPeeringConnectionResult>("sbercloud:index/getVpcPeeringConnection:getVpcPeeringConnection", args ?? new GetVpcPeeringConnectionInvokeArgs(), options.WithDefaults());

        public static Output<GetVpcPeeringConnectionResult> Invoke(GetVpcPeeringConnectionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcPeeringConnectionResult>("sbercloud:index/getVpcPeeringConnection:getVpcPeeringConnection", args ?? new GetVpcPeeringConnectionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVpcPeeringConnectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        [Input("name")]
        public string? Name { get; set; }

        [Input("peerTenantId")]
        public string? PeerTenantId { get; set; }

        [Input("peerVpcId")]
        public string? PeerVpcId { get; set; }

        [Input("region")]
        public string? Region { get; set; }

        [Input("status")]
        public string? Status { get; set; }

        [Input("vpcId")]
        public string? VpcId { get; set; }

        public GetVpcPeeringConnectionArgs()
        {
        }
        public static new GetVpcPeeringConnectionArgs Empty => new GetVpcPeeringConnectionArgs();
    }

    public sealed class GetVpcPeeringConnectionInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("peerTenantId")]
        public Input<string>? PeerTenantId { get; set; }

        [Input("peerVpcId")]
        public Input<string>? PeerVpcId { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        public GetVpcPeeringConnectionInvokeArgs()
        {
        }
        public static new GetVpcPeeringConnectionInvokeArgs Empty => new GetVpcPeeringConnectionInvokeArgs();
    }


    [OutputType]
    public sealed class GetVpcPeeringConnectionResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;
        public readonly string PeerTenantId;
        public readonly string PeerVpcId;
        public readonly string Region;
        public readonly string Status;
        public readonly string VpcId;

        [OutputConstructor]
        private GetVpcPeeringConnectionResult(
            string description,

            string id,

            string name,

            string peerTenantId,

            string peerVpcId,

            string region,

            string status,

            string vpcId)
        {
            Description = description;
            Id = id;
            Name = name;
            PeerTenantId = peerTenantId;
            PeerVpcId = peerVpcId;
            Region = region;
            Status = status;
            VpcId = vpcId;
        }
    }
}
