// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud
{
    [SbercloudResourceType("sbercloud:index/swrOrganization:SwrOrganization")]
    public partial class SwrOrganization : global::Pulumi.CustomResource
    {
        [Output("creator")]
        public Output<string> Creator { get; private set; } = null!;

        [Output("loginServer")]
        public Output<string> LoginServer { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("permission")]
        public Output<string> Permission { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a SwrOrganization resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SwrOrganization(string name, SwrOrganizationArgs? args = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/swrOrganization:SwrOrganization", name, args ?? new SwrOrganizationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SwrOrganization(string name, Input<string> id, SwrOrganizationState? state = null, CustomResourceOptions? options = null)
            : base("sbercloud:index/swrOrganization:SwrOrganization", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SwrOrganization resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SwrOrganization Get(string name, Input<string> id, SwrOrganizationState? state = null, CustomResourceOptions? options = null)
        {
            return new SwrOrganization(name, id, state, options);
        }
    }

    public sealed class SwrOrganizationArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public SwrOrganizationArgs()
        {
        }
        public static new SwrOrganizationArgs Empty => new SwrOrganizationArgs();
    }

    public sealed class SwrOrganizationState : global::Pulumi.ResourceArgs
    {
        [Input("creator")]
        public Input<string>? Creator { get; set; }

        [Input("loginServer")]
        public Input<string>? LoginServer { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("permission")]
        public Input<string>? Permission { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        public SwrOrganizationState()
        {
        }
        public static new SwrOrganizationState Empty => new SwrOrganizationState();
    }
}
