// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class CfwAclRuleSequence
    {
        /// <summary>
        /// Whether to pin on bottom.
        /// </summary>
        public readonly int? Bottom;
        /// <summary>
        /// The ID of the rule that the added rule will follow.
        /// </summary>
        public readonly string? DestRuleId;
        /// <summary>
        /// Whether to pin on top.
        /// </summary>
        public readonly int? Top;

        [OutputConstructor]
        private CfwAclRuleSequence(
            int? bottom,

            string? destRuleId,

            int? top)
        {
            Bottom = bottom;
            DestRuleId = destRuleId;
            Top = top;
        }
    }
}
