// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class CfwAclRulePredefinedServiceGroups
    {
        /// <summary>
        /// The IDs of the service groups.
        /// </summary>
        public readonly ImmutableArray<string> GroupIds;
        /// <summary>
        /// The protocols used in the service groups.
        /// </summary>
        public readonly ImmutableArray<int> Protocols;

        [OutputConstructor]
        private CfwAclRulePredefinedServiceGroups(
            ImmutableArray<string> groupIds,

            ImmutableArray<int> protocols)
        {
            GroupIds = groupIds;
            Protocols = protocols;
        }
    }
}
