// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class CssClusterPublicAccess
    {
        public readonly int Bandwidth;
        public readonly string? PublicIp;
        public readonly string? Whitelist;
        public readonly bool WhitelistEnabled;

        [OutputConstructor]
        private CssClusterPublicAccess(
            int bandwidth,

            string? publicIp,

            string? whitelist,

            bool whitelistEnabled)
        {
            Bandwidth = bandwidth;
            PublicIp = publicIp;
            Whitelist = whitelist;
            WhitelistEnabled = whitelistEnabled;
        }
    }
}
