// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class CssClusterMasterNodeConfig
    {
        public readonly string Flavor;
        public readonly int InstanceNumber;
        public readonly ImmutableArray<string> ShrinkNodeIds;
        public readonly Outputs.CssClusterMasterNodeConfigVolume Volume;

        [OutputConstructor]
        private CssClusterMasterNodeConfig(
            string flavor,

            int instanceNumber,

            ImmutableArray<string> shrinkNodeIds,

            Outputs.CssClusterMasterNodeConfigVolume volume)
        {
            Flavor = flavor;
            InstanceNumber = instanceNumber;
            ShrinkNodeIds = shrinkNodeIds;
            Volume = volume;
        }
    }
}
