// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class DwsClusterVolume
    {
        /// <summary>
        /// The capacity size, in GB.
        /// </summary>
        public readonly string? Capacity;
        /// <summary>
        /// The volume type.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private DwsClusterVolume(
            string? capacity,

            string? type)
        {
            Capacity = capacity;
            Type = type;
        }
    }
}
