// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetCfwProtectionRulesRecordResult
    {
        /// <summary>
        /// The rule action type.
        /// </summary>
        public readonly string ActionType;
        /// <summary>
        /// The address type.
        /// </summary>
        public readonly int AddressType;
        /// <summary>
        /// The created time of a rule.
        /// </summary>
        public readonly string CreatedDate;
        /// <summary>
        /// The rule description.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The destination configuration.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCfwProtectionRulesRecordDestinationResult> Destinations;
        /// <summary>
        /// The direction of a rule.
        /// </summary>
        public readonly string Direction;
        /// <summary>
        /// The last open time.
        /// </summary>
        public readonly string LastOpenTime;
        /// <summary>
        /// Whether to support persistent connections.
        /// </summary>
        public readonly int LongConnectEnable;
        /// <summary>
        /// The persistent connection duration.
        /// </summary>
        public readonly int LongConnectTime;
        /// <summary>
        /// The persistent connection duration (hour).
        /// </summary>
        public readonly int LongConnectTimeHour;
        /// <summary>
        /// The persistent connection duration (minute).
        /// </summary>
        public readonly int LongConnectTimeMinute;
        /// <summary>
        /// The persistent connection duration (second).
        /// </summary>
        public readonly int LongConnectTimeSecond;
        /// <summary>
        /// The rule name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The rule ID.
        /// </summary>
        public readonly string RuleId;
        /// <summary>
        /// The service.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCfwProtectionRulesRecordServiceResult> Services;
        /// <summary>
        /// The source configuration.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetCfwProtectionRulesRecordSourceResult> Sources;
        /// <summary>
        /// The rule status.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The tag of a rule.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Tags;
        /// <summary>
        /// The rule type.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetCfwProtectionRulesRecordResult(
            string actionType,

            int addressType,

            string createdDate,

            string description,

            ImmutableArray<Outputs.GetCfwProtectionRulesRecordDestinationResult> destinations,

            string direction,

            string lastOpenTime,

            int longConnectEnable,

            int longConnectTime,

            int longConnectTimeHour,

            int longConnectTimeMinute,

            int longConnectTimeSecond,

            string name,

            string ruleId,

            ImmutableArray<Outputs.GetCfwProtectionRulesRecordServiceResult> services,

            ImmutableArray<Outputs.GetCfwProtectionRulesRecordSourceResult> sources,

            string status,

            ImmutableDictionary<string, string> tags,

            string type)
        {
            ActionType = actionType;
            AddressType = addressType;
            CreatedDate = createdDate;
            Description = description;
            Destinations = destinations;
            Direction = direction;
            LastOpenTime = lastOpenTime;
            LongConnectEnable = longConnectEnable;
            LongConnectTime = longConnectTime;
            LongConnectTimeHour = longConnectTimeHour;
            LongConnectTimeMinute = longConnectTimeMinute;
            LongConnectTimeSecond = longConnectTimeSecond;
            Name = name;
            RuleId = ruleId;
            Services = services;
            Sources = sources;
            Status = status;
            Tags = tags;
            Type = type;
        }
    }
}
