// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetCceAddonTemplateSupportVersionResult
    {
        public readonly ImmutableArray<string> BareMetals;
        public readonly ImmutableArray<string> VirtualMachines;

        [OutputConstructor]
        private GetCceAddonTemplateSupportVersionResult(
            ImmutableArray<string> bareMetals,

            ImmutableArray<string> virtualMachines)
        {
            BareMetals = bareMetals;
            VirtualMachines = virtualMachines;
        }
    }
}
