// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetCfwFirewallsRecordProtectObjectResult
    {
        /// <summary>
        /// Protected object ID
        /// </summary>
        public readonly string ObjectId;
        /// <summary>
        /// Protected object name
        /// </summary>
        public readonly string ObjectName;
        /// <summary>
        /// Project type. The options are as follows: 0: north-south; 1: east-west.
        /// </summary>
        public readonly int Type;

        [OutputConstructor]
        private GetCfwFirewallsRecordProtectObjectResult(
            string objectId,

            string objectName,

            int type)
        {
            ObjectId = objectId;
            ObjectName = objectName;
            Type = type;
        }
    }
}
