// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetCfwProtectionRulesRecordSourceRegionListResult
    {
        /// <summary>
        /// The Chinese description of a region.
        /// </summary>
        public readonly string DescriptionCn;
        /// <summary>
        /// The English description of a region.
        /// </summary>
        public readonly string DescriptionEn;
        /// <summary>
        /// The region ID.
        /// </summary>
        public readonly string RegionId;
        /// <summary>
        /// The region type.
        /// </summary>
        public readonly int RegionType;

        [OutputConstructor]
        private GetCfwProtectionRulesRecordSourceRegionListResult(
            string descriptionCn,

            string descriptionEn,

            string regionId,

            int regionType)
        {
            DescriptionCn = descriptionCn;
            DescriptionEn = descriptionEn;
            RegionId = regionId;
            RegionType = regionType;
        }
    }
}
