// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetDmsRocketmqExtendFlavorsFlavorIoResult
    {
        /// <summary>
        /// Indicates the list of availability zones with available resources.
        /// </summary>
        public readonly ImmutableArray<string> AvailableZones;
        /// <summary>
        /// Indicates the disk IO encoding.
        /// </summary>
        public readonly string StorageSpecCode;
        /// <summary>
        /// Indicates the disk type.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Indicates the list of unavailability zones with available resources.
        /// </summary>
        public readonly ImmutableArray<string> UnavailableZones;

        [OutputConstructor]
        private GetDmsRocketmqExtendFlavorsFlavorIoResult(
            ImmutableArray<string> availableZones,

            string storageSpecCode,

            string type,

            ImmutableArray<string> unavailableZones)
        {
            AvailableZones = availableZones;
            StorageSpecCode = storageSpecCode;
            Type = type;
            UnavailableZones = unavailableZones;
        }
    }
}
