// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetErRouteTablesRouteTableRouteResult
    {
        /// <summary>
        /// The details of the attachment corresponding to the route.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetErRouteTablesRouteTableRouteAttachmentResult> Attachments;
        /// <summary>
        /// The destination address (CIDR) of the route.
        /// </summary>
        public readonly string Destination;
        /// <summary>
        /// The route ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Whether route is the black hole route.
        /// </summary>
        public readonly bool IsBlackhole;
        /// <summary>
        /// The current status of the route.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetErRouteTablesRouteTableRouteResult(
            ImmutableArray<Outputs.GetErRouteTablesRouteTableRouteAttachmentResult> attachments,

            string destination,

            string id,

            bool isBlackhole,

            string status)
        {
            Attachments = attachments;
            Destination = destination;
            Id = id;
            IsBlackhole = isBlackhole;
            Status = status;
        }
    }
}
