// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetKpsKeypairsKeypairResult
    {
        public readonly string Fingerprint;
        public readonly bool IsManaged;
        public readonly string Name;
        public readonly string PublicKey;
        public readonly string Scope;

        [OutputConstructor]
        private GetKpsKeypairsKeypairResult(
            string fingerprint,

            bool isManaged,

            string name,

            string publicKey,

            string scope)
        {
            Fingerprint = fingerprint;
            IsManaged = isManaged;
            Name = name;
            PublicKey = publicKey;
            Scope = scope;
        }
    }
}
