// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetRdsStorageTypesStorageTypeResult
    {
        /// <summary>
        /// The status details of the AZs to which the specification belongs.
        /// </summary>
        public readonly ImmutableDictionary<string, string> AzStatus;
        /// <summary>
        /// Storage type.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Performance specifications.
        /// </summary>
        public readonly ImmutableArray<string> SupportComputeGroupTypes;

        [OutputConstructor]
        private GetRdsStorageTypesStorageTypeResult(
            ImmutableDictionary<string, string> azStatus,

            string name,

            ImmutableArray<string> supportComputeGroupTypes)
        {
            AzStatus = azStatus;
            Name = name;
            SupportComputeGroupTypes = supportComputeGroupTypes;
        }
    }
}
