// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Outputs
{

    [OutputType]
    public sealed class GetSfsTurboObsTargetsTargetResult
    {
        /// <summary>
        /// The creation time of the OBS target.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The linkage directory name of the OBS target.
        /// </summary>
        public readonly string FileSystemPath;
        /// <summary>
        /// The ID of the OBS target.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The detail of the OBS bucket.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSfsTurboObsTargetsTargetObResult> Obs;
        /// <summary>
        /// The status of the OBS target.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetSfsTurboObsTargetsTargetResult(
            string createdAt,

            string fileSystemPath,

            string id,

            ImmutableArray<Outputs.GetSfsTurboObsTargetsTargetObResult> obs,

            string status)
        {
            CreatedAt = createdAt;
            FileSystemPath = fileSystemPath;
            Id = id;
            Obs = obs;
            Status = status;
        }
    }
}
