# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCfwIpsRuleDetailsResult',
    'AwaitableGetCfwIpsRuleDetailsResult',
    'get_cfw_ips_rule_details',
    'get_cfw_ips_rule_details_output',
]

@pulumi.output_type
class GetCfwIpsRuleDetailsResult:
    """
    A collection of values returned by getCfwIpsRuleDetails.
    """
    def __init__(__self__, datas=None, fw_instance_id=None, id=None, region=None):
        if datas and not isinstance(datas, list):
            raise TypeError("Expected argument 'datas' to be a list")
        pulumi.set(__self__, "datas", datas)
        if fw_instance_id and not isinstance(fw_instance_id, str):
            raise TypeError("Expected argument 'fw_instance_id' to be a str")
        pulumi.set(__self__, "fw_instance_id", fw_instance_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @property
    @pulumi.getter
    def datas(self) -> Sequence['outputs.GetCfwIpsRuleDetailsDataResult']:
        return pulumi.get(self, "datas")

    @property
    @pulumi.getter(name="fwInstanceId")
    def fw_instance_id(self) -> builtins.str:
        return pulumi.get(self, "fw_instance_id")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def region(self) -> builtins.str:
        return pulumi.get(self, "region")


class AwaitableGetCfwIpsRuleDetailsResult(GetCfwIpsRuleDetailsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCfwIpsRuleDetailsResult(
            datas=self.datas,
            fw_instance_id=self.fw_instance_id,
            id=self.id,
            region=self.region)


def get_cfw_ips_rule_details(fw_instance_id: Optional[builtins.str] = None,
                             region: Optional[builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCfwIpsRuleDetailsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['fwInstanceId'] = fw_instance_id
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sbercloud:index/getCfwIpsRuleDetails:getCfwIpsRuleDetails', __args__, opts=opts, typ=GetCfwIpsRuleDetailsResult).value

    return AwaitableGetCfwIpsRuleDetailsResult(
        datas=pulumi.get(__ret__, 'datas'),
        fw_instance_id=pulumi.get(__ret__, 'fw_instance_id'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'))
def get_cfw_ips_rule_details_output(fw_instance_id: Optional[pulumi.Input[builtins.str]] = None,
                                    region: Optional[pulumi.Input[Optional[builtins.str]]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCfwIpsRuleDetailsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['fwInstanceId'] = fw_instance_id
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('sbercloud:index/getCfwIpsRuleDetails:getCfwIpsRuleDetails', __args__, opts=opts, typ=GetCfwIpsRuleDetailsResult)
    return __ret__.apply(lambda __response__: GetCfwIpsRuleDetailsResult(
        datas=pulumi.get(__response__, 'datas'),
        fw_instance_id=pulumi.get(__response__, 'fw_instance_id'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region')))
