// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Inputs
{

    public sealed class ApigChannelMicroserviceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The CCE microservice details.
        /// </summary>
        [Input("cceConfig")]
        public Input<Inputs.ApigChannelMicroserviceCceConfigGetArgs>? CceConfig { get; set; }

        /// <summary>
        /// schema:Internal; The CSE microservice details.
        /// </summary>
        [Input("cseConfig")]
        public Input<Inputs.ApigChannelMicroserviceCseConfigGetArgs>? CseConfig { get; set; }

        public ApigChannelMicroserviceGetArgs()
        {
        }
        public static new ApigChannelMicroserviceGetArgs Empty => new ApigChannelMicroserviceGetArgs();
    }
}
