// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Inputs
{

    public sealed class CceNodePoolExtensionScaleGroupSpecAutoscalingArgs : global::Pulumi.ResourceArgs
    {
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        [Input("extensionPriority")]
        public Input<int>? ExtensionPriority { get; set; }

        [Input("maxNodeCount")]
        public Input<int>? MaxNodeCount { get; set; }

        [Input("minNodeCount")]
        public Input<int>? MinNodeCount { get; set; }

        public CceNodePoolExtensionScaleGroupSpecAutoscalingArgs()
        {
        }
        public static new CceNodePoolExtensionScaleGroupSpecAutoscalingArgs Empty => new CceNodePoolExtensionScaleGroupSpecAutoscalingArgs();
    }
}
