// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Inputs
{

    public sealed class CfwAclRuleCustomServiceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The destination port.
        /// </summary>
        [Input("destPort", required: true)]
        public Input<string> DestPort { get; set; } = null!;

        /// <summary>
        /// The protocol type.
        /// </summary>
        [Input("protocol", required: true)]
        public Input<int> Protocol { get; set; } = null!;

        /// <summary>
        /// The source port.
        /// </summary>
        [Input("sourcePort", required: true)]
        public Input<string> SourcePort { get; set; } = null!;

        public CfwAclRuleCustomServiceGetArgs()
        {
        }
        public static new CfwAclRuleCustomServiceGetArgs Empty => new CfwAclRuleCustomServiceGetArgs();
    }
}
