// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Inputs
{

    public sealed class DmsKafkaInstancePortProtocolArgs : global::Pulumi.ResourceArgs
    {
        [Input("privatePlainAddress")]
        public Input<string>? PrivatePlainAddress { get; set; }

        [Input("privatePlainDomainName")]
        public Input<string>? PrivatePlainDomainName { get; set; }

        [Input("privatePlainEnable")]
        public Input<bool>? PrivatePlainEnable { get; set; }

        [Input("privateSaslPlaintextAddress")]
        public Input<string>? PrivateSaslPlaintextAddress { get; set; }

        [Input("privateSaslPlaintextDomainName")]
        public Input<string>? PrivateSaslPlaintextDomainName { get; set; }

        [Input("privateSaslPlaintextEnable")]
        public Input<bool>? PrivateSaslPlaintextEnable { get; set; }

        [Input("privateSaslSslAddress")]
        public Input<string>? PrivateSaslSslAddress { get; set; }

        [Input("privateSaslSslDomainName")]
        public Input<string>? PrivateSaslSslDomainName { get; set; }

        [Input("privateSaslSslEnable")]
        public Input<bool>? PrivateSaslSslEnable { get; set; }

        [Input("publicPlainAddress")]
        public Input<string>? PublicPlainAddress { get; set; }

        [Input("publicPlainDomainName")]
        public Input<string>? PublicPlainDomainName { get; set; }

        [Input("publicPlainEnable")]
        public Input<bool>? PublicPlainEnable { get; set; }

        [Input("publicSaslPlaintextAddress")]
        public Input<string>? PublicSaslPlaintextAddress { get; set; }

        [Input("publicSaslPlaintextDomainName")]
        public Input<string>? PublicSaslPlaintextDomainName { get; set; }

        [Input("publicSaslPlaintextEnable")]
        public Input<bool>? PublicSaslPlaintextEnable { get; set; }

        [Input("publicSaslSslAddress")]
        public Input<string>? PublicSaslSslAddress { get; set; }

        [Input("publicSaslSslDomainName")]
        public Input<string>? PublicSaslSslDomainName { get; set; }

        [Input("publicSaslSslEnable")]
        public Input<bool>? PublicSaslSslEnable { get; set; }

        public DmsKafkaInstancePortProtocolArgs()
        {
        }
        public static new DmsKafkaInstancePortProtocolArgs Empty => new DmsKafkaInstancePortProtocolArgs();
    }
}
