// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sbercloud.Inputs
{

    public sealed class SwrOrganizationPermissionsSelfPermissionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("permission")]
        public Input<string>? Permission { get; set; }

        [Input("userId")]
        public Input<string>? UserId { get; set; }

        [Input("userName")]
        public Input<string>? UserName { get; set; }

        public SwrOrganizationPermissionsSelfPermissionGetArgs()
        {
        }
        public static new SwrOrganizationPermissionsSelfPermissionGetArgs Empty => new SwrOrganizationPermissionsSelfPermissionGetArgs();
    }
}
