// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCfwResourceTags(args: GetCfwResourceTagsArgs, opts?: pulumi.InvokeOptions): Promise<GetCfwResourceTagsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sbercloud:index/getCfwResourceTags:getCfwResourceTags", {
        "fwInstanceId": args.fwInstanceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getCfwResourceTags.
 */
export interface GetCfwResourceTagsArgs {
    fwInstanceId: string;
    region?: string;
}

/**
 * A collection of values returned by getCfwResourceTags.
 */
export interface GetCfwResourceTagsResult {
    readonly fwInstanceId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly region: string;
    readonly tags: outputs.GetCfwResourceTagsTag[];
}
export function getCfwResourceTagsOutput(args: GetCfwResourceTagsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCfwResourceTagsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sbercloud:index/getCfwResourceTags:getCfwResourceTags", {
        "fwInstanceId": args.fwInstanceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getCfwResourceTags.
 */
export interface GetCfwResourceTagsOutputArgs {
    fwInstanceId: pulumi.Input<string>;
    region?: pulumi.Input<string>;
}
