// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDdsFlavors(args: GetDdsFlavorsArgs, opts?: pulumi.InvokeOptions): Promise<GetDdsFlavorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sbercloud:index/getDdsFlavors:getDdsFlavors", {
        "engineName": args.engineName,
        "memory": args.memory,
        "region": args.region,
        "type": args.type,
        "vcpus": args.vcpus,
    }, opts);
}

/**
 * A collection of arguments for invoking getDdsFlavors.
 */
export interface GetDdsFlavorsArgs {
    engineName: string;
    memory?: string;
    region?: string;
    type?: string;
    vcpus?: string;
}

/**
 * A collection of values returned by getDdsFlavors.
 */
export interface GetDdsFlavorsResult {
    readonly engineName: string;
    readonly flavors: outputs.GetDdsFlavorsFlavor[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly memory?: string;
    readonly region: string;
    readonly type?: string;
    readonly vcpus?: string;
}
export function getDdsFlavorsOutput(args: GetDdsFlavorsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDdsFlavorsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sbercloud:index/getDdsFlavors:getDdsFlavors", {
        "engineName": args.engineName,
        "memory": args.memory,
        "region": args.region,
        "type": args.type,
        "vcpus": args.vcpus,
    }, opts);
}

/**
 * A collection of arguments for invoking getDdsFlavors.
 */
export interface GetDdsFlavorsOutputArgs {
    engineName: pulumi.Input<string>;
    memory?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    vcpus?: pulumi.Input<string>;
}
