// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IdentityAccessKey extends pulumi.CustomResource {
    /**
     * Get an existing IdentityAccessKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityAccessKeyState, opts?: pulumi.CustomResourceOptions): IdentityAccessKey {
        return new IdentityAccessKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sbercloud:index/identityAccessKey:IdentityAccessKey';

    /**
     * Returns true if the given object is an instance of IdentityAccessKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityAccessKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityAccessKey.__pulumiType;
    }

    public /*out*/ readonly createTime!: pulumi.Output<string>;
    public readonly description!: pulumi.Output<string | undefined>;
    public /*out*/ readonly encryptedSecret!: pulumi.Output<string>;
    public /*out*/ readonly keyFingerprint!: pulumi.Output<string>;
    public readonly pgpKey!: pulumi.Output<string | undefined>;
    public /*out*/ readonly secret!: pulumi.Output<string>;
    public readonly secretFile!: pulumi.Output<string | undefined>;
    public readonly status!: pulumi.Output<string>;
    public readonly userId!: pulumi.Output<string>;
    public /*out*/ readonly userName!: pulumi.Output<string>;

    /**
     * Create a IdentityAccessKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityAccessKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityAccessKeyArgs | IdentityAccessKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityAccessKeyState | undefined;
            resourceInputs["createTime"] = state ? state.createTime : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["encryptedSecret"] = state ? state.encryptedSecret : undefined;
            resourceInputs["keyFingerprint"] = state ? state.keyFingerprint : undefined;
            resourceInputs["pgpKey"] = state ? state.pgpKey : undefined;
            resourceInputs["secret"] = state ? state.secret : undefined;
            resourceInputs["secretFile"] = state ? state.secretFile : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["userId"] = state ? state.userId : undefined;
            resourceInputs["userName"] = state ? state.userName : undefined;
        } else {
            const args = argsOrState as IdentityAccessKeyArgs | undefined;
            if ((!args || args.userId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userId'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["pgpKey"] = args ? args.pgpKey : undefined;
            resourceInputs["secretFile"] = args ? args.secretFile : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
            resourceInputs["userId"] = args ? args.userId : undefined;
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["encryptedSecret"] = undefined /*out*/;
            resourceInputs["keyFingerprint"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
            resourceInputs["userName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IdentityAccessKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IdentityAccessKey resources.
 */
export interface IdentityAccessKeyState {
    createTime?: pulumi.Input<string>;
    description?: pulumi.Input<string>;
    encryptedSecret?: pulumi.Input<string>;
    keyFingerprint?: pulumi.Input<string>;
    pgpKey?: pulumi.Input<string>;
    secret?: pulumi.Input<string>;
    secretFile?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    userId?: pulumi.Input<string>;
    userName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IdentityAccessKey resource.
 */
export interface IdentityAccessKeyArgs {
    description?: pulumi.Input<string>;
    pgpKey?: pulumi.Input<string>;
    secretFile?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    userId: pulumi.Input<string>;
}
