// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RdsMysqlDatabaseTableRestore extends pulumi.CustomResource {
    /**
     * Get an existing RdsMysqlDatabaseTableRestore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RdsMysqlDatabaseTableRestoreState, opts?: pulumi.CustomResourceOptions): RdsMysqlDatabaseTableRestore {
        return new RdsMysqlDatabaseTableRestore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sbercloud:index/rdsMysqlDatabaseTableRestore:RdsMysqlDatabaseTableRestore';

    /**
     * Returns true if the given object is an instance of RdsMysqlDatabaseTableRestore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RdsMysqlDatabaseTableRestore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RdsMysqlDatabaseTableRestore.__pulumiType;
    }

    /**
     * Specifies the databases that will be restored.
     */
    public readonly databases!: pulumi.Output<outputs.RdsMysqlDatabaseTableRestoreDatabase[] | undefined>;
    /**
     * Specifies the ID of RDS MySQL instance.
     */
    public readonly instanceId!: pulumi.Output<string>;
    /**
     * Specifies whether to use fast restoration.
     */
    public readonly isFastRestore!: pulumi.Output<boolean | undefined>;
    public readonly region!: pulumi.Output<string>;
    /**
     * Specifies the tables that will be restored.
     */
    public readonly restoreTables!: pulumi.Output<outputs.RdsMysqlDatabaseTableRestoreRestoreTable[] | undefined>;
    /**
     * Specifies the restoration time point.
     */
    public readonly restoreTime!: pulumi.Output<number>;

    /**
     * Create a RdsMysqlDatabaseTableRestore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RdsMysqlDatabaseTableRestoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RdsMysqlDatabaseTableRestoreArgs | RdsMysqlDatabaseTableRestoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RdsMysqlDatabaseTableRestoreState | undefined;
            resourceInputs["databases"] = state ? state.databases : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["isFastRestore"] = state ? state.isFastRestore : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["restoreTables"] = state ? state.restoreTables : undefined;
            resourceInputs["restoreTime"] = state ? state.restoreTime : undefined;
        } else {
            const args = argsOrState as RdsMysqlDatabaseTableRestoreArgs | undefined;
            if ((!args || args.instanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            if ((!args || args.restoreTime === undefined) && !opts.urn) {
                throw new Error("Missing required property 'restoreTime'");
            }
            resourceInputs["databases"] = args ? args.databases : undefined;
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["isFastRestore"] = args ? args.isFastRestore : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["restoreTables"] = args ? args.restoreTables : undefined;
            resourceInputs["restoreTime"] = args ? args.restoreTime : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RdsMysqlDatabaseTableRestore.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RdsMysqlDatabaseTableRestore resources.
 */
export interface RdsMysqlDatabaseTableRestoreState {
    /**
     * Specifies the databases that will be restored.
     */
    databases?: pulumi.Input<pulumi.Input<inputs.RdsMysqlDatabaseTableRestoreDatabase>[]>;
    /**
     * Specifies the ID of RDS MySQL instance.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * Specifies whether to use fast restoration.
     */
    isFastRestore?: pulumi.Input<boolean>;
    region?: pulumi.Input<string>;
    /**
     * Specifies the tables that will be restored.
     */
    restoreTables?: pulumi.Input<pulumi.Input<inputs.RdsMysqlDatabaseTableRestoreRestoreTable>[]>;
    /**
     * Specifies the restoration time point.
     */
    restoreTime?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a RdsMysqlDatabaseTableRestore resource.
 */
export interface RdsMysqlDatabaseTableRestoreArgs {
    /**
     * Specifies the databases that will be restored.
     */
    databases?: pulumi.Input<pulumi.Input<inputs.RdsMysqlDatabaseTableRestoreDatabase>[]>;
    /**
     * Specifies the ID of RDS MySQL instance.
     */
    instanceId: pulumi.Input<string>;
    /**
     * Specifies whether to use fast restoration.
     */
    isFastRestore?: pulumi.Input<boolean>;
    region?: pulumi.Input<string>;
    /**
     * Specifies the tables that will be restored.
     */
    restoreTables?: pulumi.Input<pulumi.Input<inputs.RdsMysqlDatabaseTableRestoreRestoreTable>[]>;
    /**
     * Specifies the restoration time point.
     */
    restoreTime: pulumi.Input<number>;
}
