// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CfwCaptureTask struct {
	pulumi.CustomResourceState

	// The creation time of the capture task.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The destination configuration.
	Destination CfwCaptureTaskDestinationOutput `pulumi:"destination"`
	// The capture task duration.
	Duration       pulumi.IntOutput       `pulumi:"duration"`
	EnableForceNew pulumi.StringPtrOutput `pulumi:"enableForceNew"`
	// The ID of the firewall instance.
	FwInstanceId pulumi.StringOutput `pulumi:"fwInstanceId"`
	// The maximum number of packets captured.
	MaxPackets pulumi.IntOutput `pulumi:"maxPackets"`
	// The capture task name.
	Name   pulumi.StringOutput `pulumi:"name"`
	Region pulumi.StringOutput `pulumi:"region"`
	// The service configuration.
	Service CfwCaptureTaskServiceOutput `pulumi:"service"`
	// The source configuration.
	Source CfwCaptureTaskSourceOutput `pulumi:"source"`
	// The status of the capture task.
	Status pulumi.IntOutput `pulumi:"status"`
	// Whether to stop the capture.
	StopCapture pulumi.BoolPtrOutput `pulumi:"stopCapture"`
	// The ID of the capture task.
	TaskId pulumi.StringOutput `pulumi:"taskId"`
	// The update time of the capture task.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewCfwCaptureTask registers a new resource with the given unique name, arguments, and options.
func NewCfwCaptureTask(ctx *pulumi.Context,
	name string, args *CfwCaptureTaskArgs, opts ...pulumi.ResourceOption) (*CfwCaptureTask, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Destination == nil {
		return nil, errors.New("invalid value for required argument 'Destination'")
	}
	if args.Duration == nil {
		return nil, errors.New("invalid value for required argument 'Duration'")
	}
	if args.FwInstanceId == nil {
		return nil, errors.New("invalid value for required argument 'FwInstanceId'")
	}
	if args.MaxPackets == nil {
		return nil, errors.New("invalid value for required argument 'MaxPackets'")
	}
	if args.Service == nil {
		return nil, errors.New("invalid value for required argument 'Service'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CfwCaptureTask
	err := ctx.RegisterResource("sbercloud:index/cfwCaptureTask:CfwCaptureTask", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCfwCaptureTask gets an existing CfwCaptureTask resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCfwCaptureTask(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CfwCaptureTaskState, opts ...pulumi.ResourceOption) (*CfwCaptureTask, error) {
	var resource CfwCaptureTask
	err := ctx.ReadResource("sbercloud:index/cfwCaptureTask:CfwCaptureTask", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CfwCaptureTask resources.
type cfwCaptureTaskState struct {
	// The creation time of the capture task.
	CreatedAt *string `pulumi:"createdAt"`
	// The destination configuration.
	Destination *CfwCaptureTaskDestination `pulumi:"destination"`
	// The capture task duration.
	Duration       *int    `pulumi:"duration"`
	EnableForceNew *string `pulumi:"enableForceNew"`
	// The ID of the firewall instance.
	FwInstanceId *string `pulumi:"fwInstanceId"`
	// The maximum number of packets captured.
	MaxPackets *int `pulumi:"maxPackets"`
	// The capture task name.
	Name   *string `pulumi:"name"`
	Region *string `pulumi:"region"`
	// The service configuration.
	Service *CfwCaptureTaskService `pulumi:"service"`
	// The source configuration.
	Source *CfwCaptureTaskSource `pulumi:"source"`
	// The status of the capture task.
	Status *int `pulumi:"status"`
	// Whether to stop the capture.
	StopCapture *bool `pulumi:"stopCapture"`
	// The ID of the capture task.
	TaskId *string `pulumi:"taskId"`
	// The update time of the capture task.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type CfwCaptureTaskState struct {
	// The creation time of the capture task.
	CreatedAt pulumi.StringPtrInput
	// The destination configuration.
	Destination CfwCaptureTaskDestinationPtrInput
	// The capture task duration.
	Duration       pulumi.IntPtrInput
	EnableForceNew pulumi.StringPtrInput
	// The ID of the firewall instance.
	FwInstanceId pulumi.StringPtrInput
	// The maximum number of packets captured.
	MaxPackets pulumi.IntPtrInput
	// The capture task name.
	Name   pulumi.StringPtrInput
	Region pulumi.StringPtrInput
	// The service configuration.
	Service CfwCaptureTaskServicePtrInput
	// The source configuration.
	Source CfwCaptureTaskSourcePtrInput
	// The status of the capture task.
	Status pulumi.IntPtrInput
	// Whether to stop the capture.
	StopCapture pulumi.BoolPtrInput
	// The ID of the capture task.
	TaskId pulumi.StringPtrInput
	// The update time of the capture task.
	UpdatedAt pulumi.StringPtrInput
}

func (CfwCaptureTaskState) ElementType() reflect.Type {
	return reflect.TypeOf((*cfwCaptureTaskState)(nil)).Elem()
}

type cfwCaptureTaskArgs struct {
	// The destination configuration.
	Destination CfwCaptureTaskDestination `pulumi:"destination"`
	// The capture task duration.
	Duration       int     `pulumi:"duration"`
	EnableForceNew *string `pulumi:"enableForceNew"`
	// The ID of the firewall instance.
	FwInstanceId string `pulumi:"fwInstanceId"`
	// The maximum number of packets captured.
	MaxPackets int `pulumi:"maxPackets"`
	// The capture task name.
	Name   *string `pulumi:"name"`
	Region *string `pulumi:"region"`
	// The service configuration.
	Service CfwCaptureTaskService `pulumi:"service"`
	// The source configuration.
	Source CfwCaptureTaskSource `pulumi:"source"`
	// Whether to stop the capture.
	StopCapture *bool `pulumi:"stopCapture"`
}

// The set of arguments for constructing a CfwCaptureTask resource.
type CfwCaptureTaskArgs struct {
	// The destination configuration.
	Destination CfwCaptureTaskDestinationInput
	// The capture task duration.
	Duration       pulumi.IntInput
	EnableForceNew pulumi.StringPtrInput
	// The ID of the firewall instance.
	FwInstanceId pulumi.StringInput
	// The maximum number of packets captured.
	MaxPackets pulumi.IntInput
	// The capture task name.
	Name   pulumi.StringPtrInput
	Region pulumi.StringPtrInput
	// The service configuration.
	Service CfwCaptureTaskServiceInput
	// The source configuration.
	Source CfwCaptureTaskSourceInput
	// Whether to stop the capture.
	StopCapture pulumi.BoolPtrInput
}

func (CfwCaptureTaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cfwCaptureTaskArgs)(nil)).Elem()
}

type CfwCaptureTaskInput interface {
	pulumi.Input

	ToCfwCaptureTaskOutput() CfwCaptureTaskOutput
	ToCfwCaptureTaskOutputWithContext(ctx context.Context) CfwCaptureTaskOutput
}

func (*CfwCaptureTask) ElementType() reflect.Type {
	return reflect.TypeOf((**CfwCaptureTask)(nil)).Elem()
}

func (i *CfwCaptureTask) ToCfwCaptureTaskOutput() CfwCaptureTaskOutput {
	return i.ToCfwCaptureTaskOutputWithContext(context.Background())
}

func (i *CfwCaptureTask) ToCfwCaptureTaskOutputWithContext(ctx context.Context) CfwCaptureTaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CfwCaptureTaskOutput)
}

// CfwCaptureTaskArrayInput is an input type that accepts CfwCaptureTaskArray and CfwCaptureTaskArrayOutput values.
// You can construct a concrete instance of `CfwCaptureTaskArrayInput` via:
//
//	CfwCaptureTaskArray{ CfwCaptureTaskArgs{...} }
type CfwCaptureTaskArrayInput interface {
	pulumi.Input

	ToCfwCaptureTaskArrayOutput() CfwCaptureTaskArrayOutput
	ToCfwCaptureTaskArrayOutputWithContext(context.Context) CfwCaptureTaskArrayOutput
}

type CfwCaptureTaskArray []CfwCaptureTaskInput

func (CfwCaptureTaskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CfwCaptureTask)(nil)).Elem()
}

func (i CfwCaptureTaskArray) ToCfwCaptureTaskArrayOutput() CfwCaptureTaskArrayOutput {
	return i.ToCfwCaptureTaskArrayOutputWithContext(context.Background())
}

func (i CfwCaptureTaskArray) ToCfwCaptureTaskArrayOutputWithContext(ctx context.Context) CfwCaptureTaskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CfwCaptureTaskArrayOutput)
}

// CfwCaptureTaskMapInput is an input type that accepts CfwCaptureTaskMap and CfwCaptureTaskMapOutput values.
// You can construct a concrete instance of `CfwCaptureTaskMapInput` via:
//
//	CfwCaptureTaskMap{ "key": CfwCaptureTaskArgs{...} }
type CfwCaptureTaskMapInput interface {
	pulumi.Input

	ToCfwCaptureTaskMapOutput() CfwCaptureTaskMapOutput
	ToCfwCaptureTaskMapOutputWithContext(context.Context) CfwCaptureTaskMapOutput
}

type CfwCaptureTaskMap map[string]CfwCaptureTaskInput

func (CfwCaptureTaskMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CfwCaptureTask)(nil)).Elem()
}

func (i CfwCaptureTaskMap) ToCfwCaptureTaskMapOutput() CfwCaptureTaskMapOutput {
	return i.ToCfwCaptureTaskMapOutputWithContext(context.Background())
}

func (i CfwCaptureTaskMap) ToCfwCaptureTaskMapOutputWithContext(ctx context.Context) CfwCaptureTaskMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CfwCaptureTaskMapOutput)
}

type CfwCaptureTaskOutput struct{ *pulumi.OutputState }

func (CfwCaptureTaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CfwCaptureTask)(nil)).Elem()
}

func (o CfwCaptureTaskOutput) ToCfwCaptureTaskOutput() CfwCaptureTaskOutput {
	return o
}

func (o CfwCaptureTaskOutput) ToCfwCaptureTaskOutputWithContext(ctx context.Context) CfwCaptureTaskOutput {
	return o
}

// The creation time of the capture task.
func (o CfwCaptureTaskOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The destination configuration.
func (o CfwCaptureTaskOutput) Destination() CfwCaptureTaskDestinationOutput {
	return o.ApplyT(func(v *CfwCaptureTask) CfwCaptureTaskDestinationOutput { return v.Destination }).(CfwCaptureTaskDestinationOutput)
}

// The capture task duration.
func (o CfwCaptureTaskOutput) Duration() pulumi.IntOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.IntOutput { return v.Duration }).(pulumi.IntOutput)
}

func (o CfwCaptureTaskOutput) EnableForceNew() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringPtrOutput { return v.EnableForceNew }).(pulumi.StringPtrOutput)
}

// The ID of the firewall instance.
func (o CfwCaptureTaskOutput) FwInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.FwInstanceId }).(pulumi.StringOutput)
}

// The maximum number of packets captured.
func (o CfwCaptureTaskOutput) MaxPackets() pulumi.IntOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.IntOutput { return v.MaxPackets }).(pulumi.IntOutput)
}

// The capture task name.
func (o CfwCaptureTaskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CfwCaptureTaskOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The service configuration.
func (o CfwCaptureTaskOutput) Service() CfwCaptureTaskServiceOutput {
	return o.ApplyT(func(v *CfwCaptureTask) CfwCaptureTaskServiceOutput { return v.Service }).(CfwCaptureTaskServiceOutput)
}

// The source configuration.
func (o CfwCaptureTaskOutput) Source() CfwCaptureTaskSourceOutput {
	return o.ApplyT(func(v *CfwCaptureTask) CfwCaptureTaskSourceOutput { return v.Source }).(CfwCaptureTaskSourceOutput)
}

// The status of the capture task.
func (o CfwCaptureTaskOutput) Status() pulumi.IntOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.IntOutput { return v.Status }).(pulumi.IntOutput)
}

// Whether to stop the capture.
func (o CfwCaptureTaskOutput) StopCapture() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.BoolPtrOutput { return v.StopCapture }).(pulumi.BoolPtrOutput)
}

// The ID of the capture task.
func (o CfwCaptureTaskOutput) TaskId() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.TaskId }).(pulumi.StringOutput)
}

// The update time of the capture task.
func (o CfwCaptureTaskOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CfwCaptureTask) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type CfwCaptureTaskArrayOutput struct{ *pulumi.OutputState }

func (CfwCaptureTaskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CfwCaptureTask)(nil)).Elem()
}

func (o CfwCaptureTaskArrayOutput) ToCfwCaptureTaskArrayOutput() CfwCaptureTaskArrayOutput {
	return o
}

func (o CfwCaptureTaskArrayOutput) ToCfwCaptureTaskArrayOutputWithContext(ctx context.Context) CfwCaptureTaskArrayOutput {
	return o
}

func (o CfwCaptureTaskArrayOutput) Index(i pulumi.IntInput) CfwCaptureTaskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CfwCaptureTask {
		return vs[0].([]*CfwCaptureTask)[vs[1].(int)]
	}).(CfwCaptureTaskOutput)
}

type CfwCaptureTaskMapOutput struct{ *pulumi.OutputState }

func (CfwCaptureTaskMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CfwCaptureTask)(nil)).Elem()
}

func (o CfwCaptureTaskMapOutput) ToCfwCaptureTaskMapOutput() CfwCaptureTaskMapOutput {
	return o
}

func (o CfwCaptureTaskMapOutput) ToCfwCaptureTaskMapOutputWithContext(ctx context.Context) CfwCaptureTaskMapOutput {
	return o
}

func (o CfwCaptureTaskMapOutput) MapIndex(k pulumi.StringInput) CfwCaptureTaskOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CfwCaptureTask {
		return vs[0].(map[string]*CfwCaptureTask)[vs[1].(string)]
	}).(CfwCaptureTaskOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CfwCaptureTaskInput)(nil)).Elem(), &CfwCaptureTask{})
	pulumi.RegisterInputType(reflect.TypeOf((*CfwCaptureTaskArrayInput)(nil)).Elem(), CfwCaptureTaskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CfwCaptureTaskMapInput)(nil)).Elem(), CfwCaptureTaskMap{})
	pulumi.RegisterOutputType(CfwCaptureTaskOutput{})
	pulumi.RegisterOutputType(CfwCaptureTaskArrayOutput{})
	pulumi.RegisterOutputType(CfwCaptureTaskMapOutput{})
}
