// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDdsFlavors(ctx *pulumi.Context, args *GetDdsFlavorsArgs, opts ...pulumi.InvokeOption) (*GetDdsFlavorsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDdsFlavorsResult
	err := ctx.Invoke("sbercloud:index/getDdsFlavors:getDdsFlavors", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDdsFlavors.
type GetDdsFlavorsArgs struct {
	EngineName string  `pulumi:"engineName"`
	Memory     *string `pulumi:"memory"`
	Region     *string `pulumi:"region"`
	Type       *string `pulumi:"type"`
	Vcpus      *string `pulumi:"vcpus"`
}

// A collection of values returned by getDdsFlavors.
type GetDdsFlavorsResult struct {
	EngineName string                `pulumi:"engineName"`
	Flavors    []GetDdsFlavorsFlavor `pulumi:"flavors"`
	// The provider-assigned unique ID for this managed resource.
	Id     string  `pulumi:"id"`
	Memory *string `pulumi:"memory"`
	Region string  `pulumi:"region"`
	Type   *string `pulumi:"type"`
	Vcpus  *string `pulumi:"vcpus"`
}

func GetDdsFlavorsOutput(ctx *pulumi.Context, args GetDdsFlavorsOutputArgs, opts ...pulumi.InvokeOption) GetDdsFlavorsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDdsFlavorsResultOutput, error) {
			args := v.(GetDdsFlavorsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sbercloud:index/getDdsFlavors:getDdsFlavors", args, GetDdsFlavorsResultOutput{}, options).(GetDdsFlavorsResultOutput), nil
		}).(GetDdsFlavorsResultOutput)
}

// A collection of arguments for invoking getDdsFlavors.
type GetDdsFlavorsOutputArgs struct {
	EngineName pulumi.StringInput    `pulumi:"engineName"`
	Memory     pulumi.StringPtrInput `pulumi:"memory"`
	Region     pulumi.StringPtrInput `pulumi:"region"`
	Type       pulumi.StringPtrInput `pulumi:"type"`
	Vcpus      pulumi.StringPtrInput `pulumi:"vcpus"`
}

func (GetDdsFlavorsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDdsFlavorsArgs)(nil)).Elem()
}

// A collection of values returned by getDdsFlavors.
type GetDdsFlavorsResultOutput struct{ *pulumi.OutputState }

func (GetDdsFlavorsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDdsFlavorsResult)(nil)).Elem()
}

func (o GetDdsFlavorsResultOutput) ToGetDdsFlavorsResultOutput() GetDdsFlavorsResultOutput {
	return o
}

func (o GetDdsFlavorsResultOutput) ToGetDdsFlavorsResultOutputWithContext(ctx context.Context) GetDdsFlavorsResultOutput {
	return o
}

func (o GetDdsFlavorsResultOutput) EngineName() pulumi.StringOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) string { return v.EngineName }).(pulumi.StringOutput)
}

func (o GetDdsFlavorsResultOutput) Flavors() GetDdsFlavorsFlavorArrayOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) []GetDdsFlavorsFlavor { return v.Flavors }).(GetDdsFlavorsFlavorArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDdsFlavorsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDdsFlavorsResultOutput) Memory() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) *string { return v.Memory }).(pulumi.StringPtrOutput)
}

func (o GetDdsFlavorsResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetDdsFlavorsResultOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o GetDdsFlavorsResultOutput) Vcpus() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDdsFlavorsResult) *string { return v.Vcpus }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDdsFlavorsResultOutput{})
}
