// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetErFlowLogs(ctx *pulumi.Context, args *GetErFlowLogsArgs, opts ...pulumi.InvokeOption) (*GetErFlowLogsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetErFlowLogsResult
	err := ctx.Invoke("sbercloud:index/getErFlowLogs:getErFlowLogs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getErFlowLogs.
type GetErFlowLogsArgs struct {
	Enabled      *string `pulumi:"enabled"`
	FlowLogId    *string `pulumi:"flowLogId"`
	InstanceId   string  `pulumi:"instanceId"`
	LogGroupId   *string `pulumi:"logGroupId"`
	LogStreamId  *string `pulumi:"logStreamId"`
	Name         *string `pulumi:"name"`
	Region       *string `pulumi:"region"`
	ResourceId   *string `pulumi:"resourceId"`
	ResourceType *string `pulumi:"resourceType"`
	Status       *string `pulumi:"status"`
}

// A collection of values returned by getErFlowLogs.
type GetErFlowLogsResult struct {
	Enabled   *string                `pulumi:"enabled"`
	FlowLogId *string                `pulumi:"flowLogId"`
	FlowLogs  []GetErFlowLogsFlowLog `pulumi:"flowLogs"`
	// The provider-assigned unique ID for this managed resource.
	Id           string  `pulumi:"id"`
	InstanceId   string  `pulumi:"instanceId"`
	LogGroupId   *string `pulumi:"logGroupId"`
	LogStreamId  *string `pulumi:"logStreamId"`
	Name         *string `pulumi:"name"`
	Region       *string `pulumi:"region"`
	ResourceId   *string `pulumi:"resourceId"`
	ResourceType *string `pulumi:"resourceType"`
	Status       *string `pulumi:"status"`
}

func GetErFlowLogsOutput(ctx *pulumi.Context, args GetErFlowLogsOutputArgs, opts ...pulumi.InvokeOption) GetErFlowLogsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetErFlowLogsResultOutput, error) {
			args := v.(GetErFlowLogsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sbercloud:index/getErFlowLogs:getErFlowLogs", args, GetErFlowLogsResultOutput{}, options).(GetErFlowLogsResultOutput), nil
		}).(GetErFlowLogsResultOutput)
}

// A collection of arguments for invoking getErFlowLogs.
type GetErFlowLogsOutputArgs struct {
	Enabled      pulumi.StringPtrInput `pulumi:"enabled"`
	FlowLogId    pulumi.StringPtrInput `pulumi:"flowLogId"`
	InstanceId   pulumi.StringInput    `pulumi:"instanceId"`
	LogGroupId   pulumi.StringPtrInput `pulumi:"logGroupId"`
	LogStreamId  pulumi.StringPtrInput `pulumi:"logStreamId"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	Region       pulumi.StringPtrInput `pulumi:"region"`
	ResourceId   pulumi.StringPtrInput `pulumi:"resourceId"`
	ResourceType pulumi.StringPtrInput `pulumi:"resourceType"`
	Status       pulumi.StringPtrInput `pulumi:"status"`
}

func (GetErFlowLogsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetErFlowLogsArgs)(nil)).Elem()
}

// A collection of values returned by getErFlowLogs.
type GetErFlowLogsResultOutput struct{ *pulumi.OutputState }

func (GetErFlowLogsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetErFlowLogsResult)(nil)).Elem()
}

func (o GetErFlowLogsResultOutput) ToGetErFlowLogsResultOutput() GetErFlowLogsResultOutput {
	return o
}

func (o GetErFlowLogsResultOutput) ToGetErFlowLogsResultOutputWithContext(ctx context.Context) GetErFlowLogsResultOutput {
	return o
}

func (o GetErFlowLogsResultOutput) Enabled() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.Enabled }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) FlowLogId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.FlowLogId }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) FlowLogs() GetErFlowLogsFlowLogArrayOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) []GetErFlowLogsFlowLog { return v.FlowLogs }).(GetErFlowLogsFlowLogArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetErFlowLogsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetErFlowLogsResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) string { return v.InstanceId }).(pulumi.StringOutput)
}

func (o GetErFlowLogsResultOutput) LogGroupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.LogGroupId }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) LogStreamId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.LogStreamId }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.Region }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) ResourceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.ResourceId }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) ResourceType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.ResourceType }).(pulumi.StringPtrOutput)
}

func (o GetErFlowLogsResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetErFlowLogsResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetErFlowLogsResultOutput{})
}
