// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupImagesImage(ctx *pulumi.Context, args *LookupImagesImageArgs, opts ...pulumi.InvokeOption) (*LookupImagesImageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupImagesImageResult
	err := ctx.Invoke("sbercloud:index/getImagesImage:getImagesImage", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImagesImage.
type LookupImagesImageArgs struct {
	Architecture        *string `pulumi:"architecture"`
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	FlavorId            *string `pulumi:"flavorId"`
	ImageId             *string `pulumi:"imageId"`
	ImageType           *string `pulumi:"imageType"`
	IsWholeImage        *bool   `pulumi:"isWholeImage"`
	MostRecent          *bool   `pulumi:"mostRecent"`
	Name                *string `pulumi:"name"`
	NameRegex           *string `pulumi:"nameRegex"`
	Os                  *string `pulumi:"os"`
	OsVersion           *string `pulumi:"osVersion"`
	Owner               *string `pulumi:"owner"`
	Region              *string `pulumi:"region"`
	// Deprecated: size_max is deprecated
	SizeMax *int `pulumi:"sizeMax"`
	// Deprecated: size_min is deprecated
	SizeMin       *int    `pulumi:"sizeMin"`
	SortDirection *string `pulumi:"sortDirection"`
	SortKey       *string `pulumi:"sortKey"`
	Tag           *string `pulumi:"tag"`
	Visibility    *string `pulumi:"visibility"`
}

// A collection of values returned by getImagesImage.
type LookupImagesImageResult struct {
	ActiveAt            string  `pulumi:"activeAt"`
	Architecture        string  `pulumi:"architecture"`
	BackupId            string  `pulumi:"backupId"`
	Checksum            string  `pulumi:"checksum"`
	ContainerFormat     string  `pulumi:"containerFormat"`
	CreatedAt           string  `pulumi:"createdAt"`
	DataOrigin          string  `pulumi:"dataOrigin"`
	Description         string  `pulumi:"description"`
	DiskFormat          string  `pulumi:"diskFormat"`
	EnterpriseProjectId string  `pulumi:"enterpriseProjectId"`
	File                string  `pulumi:"file"`
	FlavorId            *string `pulumi:"flavorId"`
	// The provider-assigned unique ID for this managed resource.
	Id           string            `pulumi:"id"`
	ImageId      string            `pulumi:"imageId"`
	ImageType    string            `pulumi:"imageType"`
	IsWholeImage *bool             `pulumi:"isWholeImage"`
	MaxRamMb     int               `pulumi:"maxRamMb"`
	Metadata     map[string]string `pulumi:"metadata"`
	MinDiskGb    int               `pulumi:"minDiskGb"`
	MinRamMb     int               `pulumi:"minRamMb"`
	MostRecent   *bool             `pulumi:"mostRecent"`
	Name         string            `pulumi:"name"`
	NameRegex    *string           `pulumi:"nameRegex"`
	Os           string            `pulumi:"os"`
	OsVersion    string            `pulumi:"osVersion"`
	Owner        string            `pulumi:"owner"`
	Protected    bool              `pulumi:"protected"`
	Region       string            `pulumi:"region"`
	Schema       string            `pulumi:"schema"`
	SizeBytes    int               `pulumi:"sizeBytes"`
	// Deprecated: size_max is deprecated
	SizeMax *int `pulumi:"sizeMax"`
	// Deprecated: size_min is deprecated
	SizeMin       *int    `pulumi:"sizeMin"`
	SortDirection *string `pulumi:"sortDirection"`
	SortKey       *string `pulumi:"sortKey"`
	Status        string  `pulumi:"status"`
	Tag           *string `pulumi:"tag"`
	UpdatedAt     string  `pulumi:"updatedAt"`
	Visibility    string  `pulumi:"visibility"`
}

func LookupImagesImageOutput(ctx *pulumi.Context, args LookupImagesImageOutputArgs, opts ...pulumi.InvokeOption) LookupImagesImageResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupImagesImageResultOutput, error) {
			args := v.(LookupImagesImageArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sbercloud:index/getImagesImage:getImagesImage", args, LookupImagesImageResultOutput{}, options).(LookupImagesImageResultOutput), nil
		}).(LookupImagesImageResultOutput)
}

// A collection of arguments for invoking getImagesImage.
type LookupImagesImageOutputArgs struct {
	Architecture        pulumi.StringPtrInput `pulumi:"architecture"`
	EnterpriseProjectId pulumi.StringPtrInput `pulumi:"enterpriseProjectId"`
	FlavorId            pulumi.StringPtrInput `pulumi:"flavorId"`
	ImageId             pulumi.StringPtrInput `pulumi:"imageId"`
	ImageType           pulumi.StringPtrInput `pulumi:"imageType"`
	IsWholeImage        pulumi.BoolPtrInput   `pulumi:"isWholeImage"`
	MostRecent          pulumi.BoolPtrInput   `pulumi:"mostRecent"`
	Name                pulumi.StringPtrInput `pulumi:"name"`
	NameRegex           pulumi.StringPtrInput `pulumi:"nameRegex"`
	Os                  pulumi.StringPtrInput `pulumi:"os"`
	OsVersion           pulumi.StringPtrInput `pulumi:"osVersion"`
	Owner               pulumi.StringPtrInput `pulumi:"owner"`
	Region              pulumi.StringPtrInput `pulumi:"region"`
	// Deprecated: size_max is deprecated
	SizeMax pulumi.IntPtrInput `pulumi:"sizeMax"`
	// Deprecated: size_min is deprecated
	SizeMin       pulumi.IntPtrInput    `pulumi:"sizeMin"`
	SortDirection pulumi.StringPtrInput `pulumi:"sortDirection"`
	SortKey       pulumi.StringPtrInput `pulumi:"sortKey"`
	Tag           pulumi.StringPtrInput `pulumi:"tag"`
	Visibility    pulumi.StringPtrInput `pulumi:"visibility"`
}

func (LookupImagesImageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImagesImageArgs)(nil)).Elem()
}

// A collection of values returned by getImagesImage.
type LookupImagesImageResultOutput struct{ *pulumi.OutputState }

func (LookupImagesImageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImagesImageResult)(nil)).Elem()
}

func (o LookupImagesImageResultOutput) ToLookupImagesImageResultOutput() LookupImagesImageResultOutput {
	return o
}

func (o LookupImagesImageResultOutput) ToLookupImagesImageResultOutputWithContext(ctx context.Context) LookupImagesImageResultOutput {
	return o
}

func (o LookupImagesImageResultOutput) ActiveAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.ActiveAt }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Architecture() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Architecture }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) BackupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.BackupId }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Checksum() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Checksum }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) ContainerFormat() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.ContainerFormat }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) DataOrigin() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.DataOrigin }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) DiskFormat() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.DiskFormat }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) EnterpriseProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.EnterpriseProjectId }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) File() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.File }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) FlavorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *string { return v.FlavorId }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupImagesImageResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.ImageId }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) ImageType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.ImageType }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) IsWholeImage() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *bool { return v.IsWholeImage }).(pulumi.BoolPtrOutput)
}

func (o LookupImagesImageResultOutput) MaxRamMb() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImagesImageResult) int { return v.MaxRamMb }).(pulumi.IntOutput)
}

func (o LookupImagesImageResultOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupImagesImageResult) map[string]string { return v.Metadata }).(pulumi.StringMapOutput)
}

func (o LookupImagesImageResultOutput) MinDiskGb() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImagesImageResult) int { return v.MinDiskGb }).(pulumi.IntOutput)
}

func (o LookupImagesImageResultOutput) MinRamMb() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImagesImageResult) int { return v.MinRamMb }).(pulumi.IntOutput)
}

func (o LookupImagesImageResultOutput) MostRecent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *bool { return v.MostRecent }).(pulumi.BoolPtrOutput)
}

func (o LookupImagesImageResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

func (o LookupImagesImageResultOutput) Os() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Os }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) OsVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.OsVersion }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Owner }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Protected() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImagesImageResult) bool { return v.Protected }).(pulumi.BoolOutput)
}

func (o LookupImagesImageResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Schema() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Schema }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) SizeBytes() pulumi.IntOutput {
	return o.ApplyT(func(v LookupImagesImageResult) int { return v.SizeBytes }).(pulumi.IntOutput)
}

// Deprecated: size_max is deprecated
func (o LookupImagesImageResultOutput) SizeMax() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *int { return v.SizeMax }).(pulumi.IntPtrOutput)
}

// Deprecated: size_min is deprecated
func (o LookupImagesImageResultOutput) SizeMin() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *int { return v.SizeMin }).(pulumi.IntPtrOutput)
}

func (o LookupImagesImageResultOutput) SortDirection() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *string { return v.SortDirection }).(pulumi.StringPtrOutput)
}

func (o LookupImagesImageResultOutput) SortKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *string { return v.SortKey }).(pulumi.StringPtrOutput)
}

func (o LookupImagesImageResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Tag() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImagesImageResult) *string { return v.Tag }).(pulumi.StringPtrOutput)
}

func (o LookupImagesImageResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupImagesImageResultOutput) Visibility() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImagesImageResult) string { return v.Visibility }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupImagesImageResultOutput{})
}
