// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetworkingPort(ctx *pulumi.Context, args *GetNetworkingPortArgs, opts ...pulumi.InvokeOption) (*GetNetworkingPortResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetNetworkingPortResult
	err := ctx.Invoke("sbercloud:index/getNetworkingPort:getNetworkingPort", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkingPort.
type GetNetworkingPortArgs struct {
	// Deprecated: this field is deprecated
	AdminStateUp *bool   `pulumi:"adminStateUp"`
	DeviceId     *string `pulumi:"deviceId"`
	DeviceOwner  *string `pulumi:"deviceOwner"`
	FixedIp      *string `pulumi:"fixedIp"`
	MacAddress   *string `pulumi:"macAddress"`
	Name         *string `pulumi:"name"`
	NetworkId    *string `pulumi:"networkId"`
	PortId       *string `pulumi:"portId"`
	// Deprecated: this field is deprecated
	ProjectId        *string  `pulumi:"projectId"`
	Region           *string  `pulumi:"region"`
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	Status           *string  `pulumi:"status"`
	// Deprecated: this field is deprecated
	TenantId *string `pulumi:"tenantId"`
}

// A collection of values returned by getNetworkingPort.
type GetNetworkingPortResult struct {
	// Deprecated: this field is deprecated
	AdminStateUp        bool     `pulumi:"adminStateUp"`
	AllAllowedIps       []string `pulumi:"allAllowedIps"`
	AllFixedIps         []string `pulumi:"allFixedIps"`
	AllSecurityGroupIds []string `pulumi:"allSecurityGroupIds"`
	DeviceId            string   `pulumi:"deviceId"`
	DeviceOwner         string   `pulumi:"deviceOwner"`
	FixedIp             *string  `pulumi:"fixedIp"`
	// The provider-assigned unique ID for this managed resource.
	Id         string `pulumi:"id"`
	MacAddress string `pulumi:"macAddress"`
	Name       string `pulumi:"name"`
	NetworkId  string `pulumi:"networkId"`
	PortId     string `pulumi:"portId"`
	// Deprecated: this field is deprecated
	ProjectId        *string  `pulumi:"projectId"`
	Region           string   `pulumi:"region"`
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	Status           string   `pulumi:"status"`
	// Deprecated: this field is deprecated
	TenantId *string `pulumi:"tenantId"`
}

func GetNetworkingPortOutput(ctx *pulumi.Context, args GetNetworkingPortOutputArgs, opts ...pulumi.InvokeOption) GetNetworkingPortResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetworkingPortResultOutput, error) {
			args := v.(GetNetworkingPortArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sbercloud:index/getNetworkingPort:getNetworkingPort", args, GetNetworkingPortResultOutput{}, options).(GetNetworkingPortResultOutput), nil
		}).(GetNetworkingPortResultOutput)
}

// A collection of arguments for invoking getNetworkingPort.
type GetNetworkingPortOutputArgs struct {
	// Deprecated: this field is deprecated
	AdminStateUp pulumi.BoolPtrInput   `pulumi:"adminStateUp"`
	DeviceId     pulumi.StringPtrInput `pulumi:"deviceId"`
	DeviceOwner  pulumi.StringPtrInput `pulumi:"deviceOwner"`
	FixedIp      pulumi.StringPtrInput `pulumi:"fixedIp"`
	MacAddress   pulumi.StringPtrInput `pulumi:"macAddress"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	NetworkId    pulumi.StringPtrInput `pulumi:"networkId"`
	PortId       pulumi.StringPtrInput `pulumi:"portId"`
	// Deprecated: this field is deprecated
	ProjectId        pulumi.StringPtrInput   `pulumi:"projectId"`
	Region           pulumi.StringPtrInput   `pulumi:"region"`
	SecurityGroupIds pulumi.StringArrayInput `pulumi:"securityGroupIds"`
	Status           pulumi.StringPtrInput   `pulumi:"status"`
	// Deprecated: this field is deprecated
	TenantId pulumi.StringPtrInput `pulumi:"tenantId"`
}

func (GetNetworkingPortOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkingPortArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkingPort.
type GetNetworkingPortResultOutput struct{ *pulumi.OutputState }

func (GetNetworkingPortResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkingPortResult)(nil)).Elem()
}

func (o GetNetworkingPortResultOutput) ToGetNetworkingPortResultOutput() GetNetworkingPortResultOutput {
	return o
}

func (o GetNetworkingPortResultOutput) ToGetNetworkingPortResultOutputWithContext(ctx context.Context) GetNetworkingPortResultOutput {
	return o
}

// Deprecated: this field is deprecated
func (o GetNetworkingPortResultOutput) AdminStateUp() pulumi.BoolOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) bool { return v.AdminStateUp }).(pulumi.BoolOutput)
}

func (o GetNetworkingPortResultOutput) AllAllowedIps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) []string { return v.AllAllowedIps }).(pulumi.StringArrayOutput)
}

func (o GetNetworkingPortResultOutput) AllFixedIps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) []string { return v.AllFixedIps }).(pulumi.StringArrayOutput)
}

func (o GetNetworkingPortResultOutput) AllSecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) []string { return v.AllSecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o GetNetworkingPortResultOutput) DeviceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.DeviceId }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) DeviceOwner() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.DeviceOwner }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) FixedIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) *string { return v.FixedIp }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetNetworkingPortResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.MacAddress }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.NetworkId }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) PortId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.PortId }).(pulumi.StringOutput)
}

// Deprecated: this field is deprecated
func (o GetNetworkingPortResultOutput) ProjectId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) *string { return v.ProjectId }).(pulumi.StringPtrOutput)
}

func (o GetNetworkingPortResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetNetworkingPortResultOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) []string { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o GetNetworkingPortResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) string { return v.Status }).(pulumi.StringOutput)
}

// Deprecated: this field is deprecated
func (o GetNetworkingPortResultOutput) TenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkingPortResult) *string { return v.TenantId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetworkingPortResultOutput{})
}
