// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sbercloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/masikrus/pulumi-sbercloud/sdk/go/sbercloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LbCertificate struct {
	pulumi.CustomResourceState

	Certificate         pulumi.StringOutput    `pulumi:"certificate"`
	CreateTime          pulumi.StringOutput    `pulumi:"createTime"`
	Description         pulumi.StringPtrOutput `pulumi:"description"`
	Domain              pulumi.StringPtrOutput `pulumi:"domain"`
	EnterpriseProjectId pulumi.StringOutput    `pulumi:"enterpriseProjectId"`
	ExpireTime          pulumi.StringOutput    `pulumi:"expireTime"`
	Name                pulumi.StringOutput    `pulumi:"name"`
	PrivateKey          pulumi.StringPtrOutput `pulumi:"privateKey"`
	Region              pulumi.StringOutput    `pulumi:"region"`
	Type                pulumi.StringPtrOutput `pulumi:"type"`
	UpdateTime          pulumi.StringOutput    `pulumi:"updateTime"`
}

// NewLbCertificate registers a new resource with the given unique name, arguments, and options.
func NewLbCertificate(ctx *pulumi.Context,
	name string, args *LbCertificateArgs, opts ...pulumi.ResourceOption) (*LbCertificate, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Certificate == nil {
		return nil, errors.New("invalid value for required argument 'Certificate'")
	}
	if args.Certificate != nil {
		args.Certificate = pulumi.ToSecret(args.Certificate).(pulumi.StringInput)
	}
	if args.PrivateKey != nil {
		args.PrivateKey = pulumi.ToSecret(args.PrivateKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"certificate",
		"privateKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LbCertificate
	err := ctx.RegisterResource("sbercloud:index/lbCertificate:LbCertificate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLbCertificate gets an existing LbCertificate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLbCertificate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LbCertificateState, opts ...pulumi.ResourceOption) (*LbCertificate, error) {
	var resource LbCertificate
	err := ctx.ReadResource("sbercloud:index/lbCertificate:LbCertificate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LbCertificate resources.
type lbCertificateState struct {
	Certificate         *string `pulumi:"certificate"`
	CreateTime          *string `pulumi:"createTime"`
	Description         *string `pulumi:"description"`
	Domain              *string `pulumi:"domain"`
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	ExpireTime          *string `pulumi:"expireTime"`
	Name                *string `pulumi:"name"`
	PrivateKey          *string `pulumi:"privateKey"`
	Region              *string `pulumi:"region"`
	Type                *string `pulumi:"type"`
	UpdateTime          *string `pulumi:"updateTime"`
}

type LbCertificateState struct {
	Certificate         pulumi.StringPtrInput
	CreateTime          pulumi.StringPtrInput
	Description         pulumi.StringPtrInput
	Domain              pulumi.StringPtrInput
	EnterpriseProjectId pulumi.StringPtrInput
	ExpireTime          pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	PrivateKey          pulumi.StringPtrInput
	Region              pulumi.StringPtrInput
	Type                pulumi.StringPtrInput
	UpdateTime          pulumi.StringPtrInput
}

func (LbCertificateState) ElementType() reflect.Type {
	return reflect.TypeOf((*lbCertificateState)(nil)).Elem()
}

type lbCertificateArgs struct {
	Certificate         string  `pulumi:"certificate"`
	Description         *string `pulumi:"description"`
	Domain              *string `pulumi:"domain"`
	EnterpriseProjectId *string `pulumi:"enterpriseProjectId"`
	Name                *string `pulumi:"name"`
	PrivateKey          *string `pulumi:"privateKey"`
	Region              *string `pulumi:"region"`
	Type                *string `pulumi:"type"`
}

// The set of arguments for constructing a LbCertificate resource.
type LbCertificateArgs struct {
	Certificate         pulumi.StringInput
	Description         pulumi.StringPtrInput
	Domain              pulumi.StringPtrInput
	EnterpriseProjectId pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	PrivateKey          pulumi.StringPtrInput
	Region              pulumi.StringPtrInput
	Type                pulumi.StringPtrInput
}

func (LbCertificateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lbCertificateArgs)(nil)).Elem()
}

type LbCertificateInput interface {
	pulumi.Input

	ToLbCertificateOutput() LbCertificateOutput
	ToLbCertificateOutputWithContext(ctx context.Context) LbCertificateOutput
}

func (*LbCertificate) ElementType() reflect.Type {
	return reflect.TypeOf((**LbCertificate)(nil)).Elem()
}

func (i *LbCertificate) ToLbCertificateOutput() LbCertificateOutput {
	return i.ToLbCertificateOutputWithContext(context.Background())
}

func (i *LbCertificate) ToLbCertificateOutputWithContext(ctx context.Context) LbCertificateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbCertificateOutput)
}

// LbCertificateArrayInput is an input type that accepts LbCertificateArray and LbCertificateArrayOutput values.
// You can construct a concrete instance of `LbCertificateArrayInput` via:
//
//	LbCertificateArray{ LbCertificateArgs{...} }
type LbCertificateArrayInput interface {
	pulumi.Input

	ToLbCertificateArrayOutput() LbCertificateArrayOutput
	ToLbCertificateArrayOutputWithContext(context.Context) LbCertificateArrayOutput
}

type LbCertificateArray []LbCertificateInput

func (LbCertificateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LbCertificate)(nil)).Elem()
}

func (i LbCertificateArray) ToLbCertificateArrayOutput() LbCertificateArrayOutput {
	return i.ToLbCertificateArrayOutputWithContext(context.Background())
}

func (i LbCertificateArray) ToLbCertificateArrayOutputWithContext(ctx context.Context) LbCertificateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbCertificateArrayOutput)
}

// LbCertificateMapInput is an input type that accepts LbCertificateMap and LbCertificateMapOutput values.
// You can construct a concrete instance of `LbCertificateMapInput` via:
//
//	LbCertificateMap{ "key": LbCertificateArgs{...} }
type LbCertificateMapInput interface {
	pulumi.Input

	ToLbCertificateMapOutput() LbCertificateMapOutput
	ToLbCertificateMapOutputWithContext(context.Context) LbCertificateMapOutput
}

type LbCertificateMap map[string]LbCertificateInput

func (LbCertificateMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LbCertificate)(nil)).Elem()
}

func (i LbCertificateMap) ToLbCertificateMapOutput() LbCertificateMapOutput {
	return i.ToLbCertificateMapOutputWithContext(context.Background())
}

func (i LbCertificateMap) ToLbCertificateMapOutputWithContext(ctx context.Context) LbCertificateMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LbCertificateMapOutput)
}

type LbCertificateOutput struct{ *pulumi.OutputState }

func (LbCertificateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LbCertificate)(nil)).Elem()
}

func (o LbCertificateOutput) ToLbCertificateOutput() LbCertificateOutput {
	return o
}

func (o LbCertificateOutput) ToLbCertificateOutputWithContext(ctx context.Context) LbCertificateOutput {
	return o
}

func (o LbCertificateOutput) Certificate() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.Certificate }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) CreateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.CreateTime }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o LbCertificateOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringPtrOutput { return v.Domain }).(pulumi.StringPtrOutput)
}

func (o LbCertificateOutput) EnterpriseProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.EnterpriseProjectId }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) ExpireTime() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.ExpireTime }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) PrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringPtrOutput { return v.PrivateKey }).(pulumi.StringPtrOutput)
}

func (o LbCertificateOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o LbCertificateOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

func (o LbCertificateOutput) UpdateTime() pulumi.StringOutput {
	return o.ApplyT(func(v *LbCertificate) pulumi.StringOutput { return v.UpdateTime }).(pulumi.StringOutput)
}

type LbCertificateArrayOutput struct{ *pulumi.OutputState }

func (LbCertificateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LbCertificate)(nil)).Elem()
}

func (o LbCertificateArrayOutput) ToLbCertificateArrayOutput() LbCertificateArrayOutput {
	return o
}

func (o LbCertificateArrayOutput) ToLbCertificateArrayOutputWithContext(ctx context.Context) LbCertificateArrayOutput {
	return o
}

func (o LbCertificateArrayOutput) Index(i pulumi.IntInput) LbCertificateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LbCertificate {
		return vs[0].([]*LbCertificate)[vs[1].(int)]
	}).(LbCertificateOutput)
}

type LbCertificateMapOutput struct{ *pulumi.OutputState }

func (LbCertificateMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LbCertificate)(nil)).Elem()
}

func (o LbCertificateMapOutput) ToLbCertificateMapOutput() LbCertificateMapOutput {
	return o
}

func (o LbCertificateMapOutput) ToLbCertificateMapOutputWithContext(ctx context.Context) LbCertificateMapOutput {
	return o
}

func (o LbCertificateMapOutput) MapIndex(k pulumi.StringInput) LbCertificateOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LbCertificate {
		return vs[0].(map[string]*LbCertificate)[vs[1].(string)]
	}).(LbCertificateOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LbCertificateInput)(nil)).Elem(), &LbCertificate{})
	pulumi.RegisterInputType(reflect.TypeOf((*LbCertificateArrayInput)(nil)).Elem(), LbCertificateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LbCertificateMapInput)(nil)).Elem(), LbCertificateMap{})
	pulumi.RegisterOutputType(LbCertificateOutput{})
	pulumi.RegisterOutputType(LbCertificateArrayOutput{})
	pulumi.RegisterOutputType(LbCertificateMapOutput{})
}
